.credo.exs, apps/common/lib/lexical/source_file/document.ex, apps/common_protocol/lib/lexical/protocol/conversions.ex, apps/proto/lib/lexical/protocol/proto/macros/message.ex, apps/proto/lib/lexical/protocol/proto/response.ex, apps/protocol/lib/lexical/protocol/json_rpc.ex, apps/protocol/test/proto_test.exs, apps/remote_control/lib/lexical/remote_control.ex, apps/remote_control/lib/lexical/remote_control/api.ex, apps/remote_control/lib/lexical/remote_control/bootstrap.ex, apps/remote_control/lib/lexical/remote_control/code_mod/format.ex, apps/remote_control/lib/lexical/remote_control/code_mod/replace_with_underscore.ex, apps/remote_control/lib/lexical/remote_control/mix.tasks.deps.safe_compile.ex, apps/remote_control/test/lexical/remote_control/build_test.exs, apps/remote_control/test/lexical/remote_control/code_mod/format_test.exs, apps/remote_control/test/lexical/remote_control_test.exs, apps/server/lib/lexical/server/code_intelligence/completion/env.ex, apps/server/lib/lexical/server/json_rpc_backend.ex, apps/server/lib/lexical/server/project/diagnostics.ex, apps/server/lib/lexical/server/provider/handlers/completion.ex, apps/server/lib/lexical/server/provider/handlers/formatting.ex, apps/server/lib/lexical/server/provider/queue.ex, apps/server/test/lexical/server/code_intelligence/completion/env_test.exs, apps/server/test/lexical/server/code_intelligence/completion_test.exs, apps/server/test/lexical/server/project/diagnostics/state_test.exs, apps/server/test/lexical/server/project/dispatch_test.exs, apps/server/test/lexical/server/provider/queue_test.exs, apps/server/test/source_file_test.exs, mix.exs
In order to get alias sorting, I enabled strict credo and fixed up the existing issues.
=> Enabled strict credo

apps/common/test/lexical/code_unit_test.exs, apps/common/test/lexical/line_parser_test.exs, apps/common/test/lexical/process_cache_test.exs, apps/protocol/test/lexical/protocol/conversions_test.exs, apps/remote_control/test/lexical/remote_control/code_mod/diff_test.exs
Skipped most of the conversions test until I reinstate the elixir <-> lsp conversions
=> Added unit tests

apps/remote_control/lib/lexical/remote_control/build.ex
=> Add exception back in, wrongfully removed

apps/common/lib/lexical/source_file/store.ex, apps/common/test/lexical/source_file/store_test.exs
=> Fix the typo of ets_put args

apps/remote_control/lib/lexical/remote_control/build/state.ex
Project-wide builds were taking around 900ms on my laptop. A lot of this time was coming from tasks that I thought should have negligible run times, like fetching deps when there were none to fetch. It turns out that they were each contributing around 250ms to the build. By moving these tasks to only run if a build is being forced, the compilation now takes around 250ms.
=> Sped up builds by moving steps to the force? path

apps/remote_control/lib/lexical/remote_control/api.ex, apps/server/lib/lexical/server/code_intelligence/completion/translations/module_or_behaviour.ex, apps/server/test/lexical/server/code_intelligence/completion/translations/struct_test.exs
Above is the current behavior, which is annoying.
=> Make adding curlies more accurate

apps/common/lib/lexical/format.ex, apps/remote_control/test/fixtures/project/lib/other_modules.ex, apps/server/lib/lexical/server/code_intelligence/completion.ex, apps/server/lib/lexical/server/code_intelligence/completion/translations/macro.ex, apps/server/lib/lexical/server/code_intelligence/completion/translations/module_or_behaviour.ex, apps/server/lib/lexical/server/code_intelligence/completion/translations/struct.ex, apps/server/lib/lexical/server/project/intelligence.ex, apps/server/test/lexical/server/code_intelligence/completion/translations/macro_test.exs, apps/server/test/lexical/server/code_intelligence/completion/translations/module_or_behaviour_test.exs, apps/server/test/lexical/server/code_intelligence/completion/translations/struct_test.exs, apps/server/test/lexical/server/project/intelligence_test.exs
Two commits here. One improves struct completions, and the other makes them snippets to put the cursor inside the curly braces when you complete.
=> Improve struct completions

apps/server/lib/lexical/server/code_intelligence/completion.ex, apps/server/lib/lexical/server/code_intelligence/completion/translations/module_or_behaviour.ex, apps/server/lib/lexical/server/project/intelligence.ex, apps/server/test/lexical/server/project/intelligence_test.exs
Refined generation specifiers
The previous specifiers were a bit opaque, with a range given to the functions. Hopefully this is a little clearer
=> Improve intelligence api

apps/remote_control/lib/lexical/remote_control/build/error.ex, apps/remote_control/test/lexical/remote_control/build/error_test.exs
=> Fix diagnostic for missing fields due to @enforce_keys

apps/protocol/lib/generated/lexical/protocol/types/did_change_watched_files/registration/options.ex, apps/protocol/lib/generated/lexical/protocol/types/file_system_watcher.ex, apps/protocol/lib/generated/lexical/protocol/types/glob_pattern.ex, apps/protocol/lib/generated/lexical/protocol/types/relative_pattern.ex, apps/protocol/lib/generated/lexical/protocol/types/watch/kind.ex, apps/protocol/lib/lexical/protocol/json_rpc.ex, apps/server/lib/lexical/server/state.ex
If the server supports it, we will now receive watched file notifications for files that have been added / updated or deleted in the project directories.
This will help determining whether we should recompile the whole project if a dependency has changed, or if we should remove a module from our compiled module cache.
=> Added file watching

apps/common/lib/lexical/document/store.ex, apps/server/lib/lexical/server.ex
Reverts the deadlocks PR, which was fixing the wrong problem.
=> Revert deadlocks

apps/common/lib/lexical/code_unit.ex
This reduces memory footprint as we can compute the code units count by using simple integer comparisons. This should result in faster code, but I haven't benchmarked it yet.
=> Do not create intermediate binaries

apps/server/mix.exs
Wx was causing problems for people compiling
fixes #199
=> Removed wx and et applications

README.md, apps/proto/lib/mix/tasks/namespace.ex, apps/proto/lib/mix/tasks/namespace/abstract.ex, apps/proto/lib/mix/tasks/namespace/beams.ex, apps/proto/lib/mix/tasks/namespace/module.ex, apps/proto/lib/mix/tasks/namespace/release.ex, apps/proto/lib/mix/tasks/namespace/task.ex, apps/remote_control/lib/lexical/remote_control/project_node.ex
As we are using relative paths, we need to rewrite the boot file and two app-related definitions and references.
Fixes #165
=> Fix the NAMESPACE=1 release issue

apps/server/lib/lexical/server/code_intelligence/completion/translations/macro.ex, apps/server/test/lexical/server/code_intelligence/completion/translations/macro_test.exs
Open PR, should be ready for test macros
=> [issue-178] Snippet translations for  macro

apps/server/test/lexical/server/code_intelligence/completion/translations/macro_test.exs
=> [issue-178] Fix macro_test

apps/plugin_runner/lib/lexical/plugin/runner.ex, apps/remote_control/lib/lexical/remote_control/build.ex, apps/remote_control/lib/lexical/remote_control/build/state.ex, apps/remote_control/lib/lexical/remote_control/code_mod/format.ex, apps/remote_control/lib/lexical/remote_control/mix.tasks.deps.safe_compile.ex, apps/remote_control/lib/lexical/remote_control/project_node.ex, apps/server/lib/lexical/server.ex, apps/server/lib/lexical/server/project/node.ex, apps/server/lib/lexical/server/provider/queue.ex, apps/server/lib/lexical/server/state.ex
Two commits, both fix compile warnings emitted by 1.15.
=> Compile warnings

apps/remote_control/lib/lexical/remote_control/code_mod/ast/aliases.ex, apps/remote_control/test/lexical/remote_control/code_mod/ast/aliases_test.exs
Built an alias module with submodules that can look at a bit of source code and determine what the aliases are at a given position
=> WIP: Alias module

apps/server/lib/lexical/server/code_intelligence/completion/translations/callable.ex, apps/server/lib/lexical/server/code_intelligence/completion/translations/macro.ex, apps/server/test/lexical/server/code_intelligence/completion/translations/macro_test.exs
Added completion helper for describe blocks and ignored syntax functions / macros.
=> Completion improvements

pages/installation.md
Thank you for your work on this library! Had a go at adding Vim-specific instructions, referencing this [issue](https://github.com/lexical-lsp/lexical/issues/228)
=> Added installation instructions for Vim + Vim-LSP

apps/remote_control/lib/mix/tasks/namespace/transform/beams.ex, apps/server/lib/mix/tasks/package.ex
=> Fix typo of package task

README.md
=> Added development docs suggestions

bin/start_lexical.sh
Seems ERL_LIBS wasn't picked up universally across versions, so I swapped that out for the -pa flag
=> Improved launcher script

apps/remote_control/lib/lexical/remote_control/application.ex, apps/remote_control/lib/lexical/remote_control/dispatch.ex
I'd like to get a 0.4 release out this week, and indexing is too immature to release right now.
=> Disabled indexing

.github/workflows/nix.yml, flake.nix, nix/hash, nix/lexical.nix
=> chore: update Nix definition

apps/remote_control/lib/lexical/remote_control/dispatch/handlers/indexing.ex, apps/remote_control/lib/lexical/remote_control/search/store.ex, apps/remote_control/lib/lexical/remote_control/search/store/backend.ex, apps/remote_control/lib/lexical/remote_control/search/store/backends/ets.ex, apps/remote_control/lib/lexical/remote_control/search/store/backends/ets/state.ex, apps/remote_control/lib/lexical/remote_control/search/store/state.ex, apps/remote_control/test/lexical/remote_control/dispatch/handlers/indexer_test.exs, apps/remote_control/test/lexical/remote_control/search/store/backends/ets_test.exs, apps/remote_control/test/lexical/remote_control/search/store_test.exs, config/test.exs, projects/lexical_test/lib/lexical/test/eventual_assertions.ex
Two commits here, unrelated. Please review separately.
=> Quiescent sync

pages/installation.md
Lexical support was added to ALE in dense-analysis/ale#4580.
=> Add Vim ALE configuration details

apps/server/lib/lexical/server/code_intelligence/completion/translations/macro.ex, apps/server/test/lexical/server/code_intelligence/completion/translations/macro_test.exs
As mentioned by scohen added this symbol :: in the list of @snippet_macros to not show any completions. 
Target issue #474 
This PR is ready for review. Feedbacks would be really helpful
=> Removed unhelpful completion for :: symbol

flake.lock, flake.nix, nix/lexical.nix
=> Move from flake-utils to flake-parts

apps/remote_control/lib/lexical/remote_control/code_action/handlers/replace_remote_function.ex, apps/remote_control/test/lexical/remote_control/code_action/handlers/replace_remote_function_test.exs
=> Make the warning: prefix optional in rename function regex

apps/server/lib/lexical/convertibles/lexical.plugin.diagnostic.result.ex, apps/server/test/lexical/convertibles/lexical.plugin.diagnostic.result_test.exs
=> Fix Diagnostic.Result to_lsp with 4-elem tuple position

flake.lock, nix/hash
=> chore(nix): update deps hash

apps/remote_control/lib/lexical/remote_control/code_action/handlers/replace_remote_function.ex, apps/remote_control/test/lexical/remote_control/code_action/handlers/replace_remote_function_test.exs
I got a crash when editing around an erlang function. It was caused by replace remote function failing because it didn't properly handle erlang modules or erlang function call shapes.
Fixes #550
=> Replace remote function now handles erlang functions

apps/remote_control/lib/lexical/remote_control/code_intelligence/entity.ex, apps/remote_control/test/lexical/remote_control/code_intelligence/entity_test.exs
=> Resolve function definitions without parens

apps/remote_control/lib/lexical/remote_control/code_intelligence/entity.ex, apps/remote_control/test/lexical/remote_control/code_intelligence/entity_test.exs
=> Correctly resolve imported calls

apps/remote_control/lib/lexical/remote_control/code_intelligence/entity.ex, apps/remote_control/test/lexical/remote_control/code_intelligence/entity_test.exs
=> Correctly resolve `&Module.function/arity` syntax

apps/remote_control/lib/lexical/remote_control/code_intelligence/docs.ex
Parse docs can fail, and it should return an error tuple rather than crashing
Fixes #571
=> Made parse_docs return an error tuple

apps/server/lib/lexical/server/code_intelligence/completion.ex
=> Bumped resolution for structs to great-grandchild

apps/remote_control/lib/lexical/remote_control/search/indexer.ex
We were indexing references for modules and functions in dependencies. This made the index much larger than it needed to be, and would cloud "find references" with references that your project didn't make. I could see it being useful in niche situations, but the default should be to not index them.
On lexical, this halves memory usage by the VM
In the future, this could be a per-project setting
Fixes #590
=> Stopped indexing references in deps

apps/remote_control/lib/lexical/remote_control/code_intelligence/entity.ex, apps/remote_control/test/lexical/remote_control/code_intelligence/entity_test.exs
=> Entity.resolve resolves defstruct correctly

apps/remote_control/lib/lexical/remote_control/code_intelligence/entity.ex, apps/remote_control/test/lexical/remote_control/code_intelligence/entity_test.exs
While trying find_references, I hovered over a zero-arg function definition, and resolution couldn't resolve it, thus i couldn't find references. This fixes resolution.
Fixes #604
=> Fix: Resolve doesn't recognize zero-arg defs as functions

pages/installation.md
as we now supported Elixir 1.16
Fixes #623
=> Update the installation documentation for the supported Elixir version

pages/architecture.md, pages/glossary.md
This is my first time working on anything LSP related, so I decided to add entries I'd find useful and descriptive as I went along learning.
=> Add more glossary entries

apps/remote_control/lib/lexical/remote_control/code_intelligence/symbols/document.ex, apps/remote_control/test/lexical/remote_control/code_intelligence/symbols_test.exs, apps/remote_control/test/test_helper.exs
=> Added def/defp to document symbols for functions

apps/server/lib/lexical/server/code_intelligence/completion/translations/macro.ex, apps/server/test/lexical/server/code_intelligence/completion/translations/macro_test.exs
=> Fix: Module suggestion was incorrect for files with multiple periods

apps/remote_control/lib/lexical/remote_control/code_mod/format.ex, apps/remote_control/lib/lexical/remote_control/completion.ex, apps/remote_control/lib/lexical/remote_control/completion/candidate.ex, apps/remote_control/test/fixtures/project/.formatter.exs, apps/remote_control/test/fixtures/project/lib/functions.ex, apps/remote_control/test/fixtures/project/lib/macros.ex, apps/server/lib/lexical/server/code_intelligence/completion/translations/callable.ex, apps/server/test/lexical/server/code_intelligence/completion/translations/function_test.exs, apps/server/test/lexical/server/code_intelligence/completion/translations/macro_test.exs
This is scratching an itch I had while I was doing some work on another library.
Fixes #601
=> Complete callables without parens if present in locals_without_parens

mix.exs
Just to sync with my shell prompt, stubbornly claiming this to be v0.5.0 still. Feel free to disregard and just update on next release :)
=> Declare v0.7.0 in mix.exs

nix/hash
The hash is outdated, so I will send you an update. #817 should fix the automation of this process.
=> Update the Nix hash
