lexical-lsp/lexical

- apps/protocol/lib/lexical/protocol/responses.ex
Types.Initizlize.Result does not exist.
> Change Types.Initizlize.Result to Types.Initialize.Result

- README.md
- apps/proto/lib/mix/tasks/namespace/abstract.ex
- apps/proto/lib/mix/tasks/namespace/release.ex
- apps/remote_control/lib/lexical/remote_control/build.ex
- mix.exs
This should be it for namespacing everything that requires namespacing.
Just added some sneaky edge cases that were not covered by previous code, the general scheme of the task stays very similar.
This fixes diagnostics that look like:
```ex
%Mix.Task.Compiler.Diagnostic{file: "/Users/steve/Projects/lexical/apps/server/lib/lexical/server/project/diagnostics.ex", severity: :warning, message: "Lexical.SourceFile.Store.open?/1 defined in application :common is used by the current application but the current application does not depend on :common. To fix this, you must do one of:\n\n  1. If :common is part of Erlang/Elixir, you must include it under :extra_applications inside \"def application\" in your mix.exs\n\n  2. If :common is a dependency, make sure it is listed under \"def deps\" in …
```
> Improve namespace for .app files & its references.

- apps/proto/lib/lexical/protocol/proto/convert.ex
- apps/proto/lib/lexical/protocol/proto/macros/inspect.ex
- apps/proto/lib/lexical/protocol/proto/response.ex
- apps/protocol/lib/lexical/protocol/ranged.ex
- apps/protocol/lib/lexical/protocol/response.ex
- apps/protocol/test/lexical/proto_test.exs
- apps/protocol/test/lexical/protocol/response_test.exs
- apps/server/lib/lexical/server/provider/queue.ex
I was noticing a lot of manual conversions in the code, and that kind of stinks. To help with this, I'm going to change how things work in the project, but this requires some additions to the protocol.
The overarching idea is to push conversions into the protocol, so that on the way in, we convert from LSP structures to native and on the way out we convert from native to LSP structures. Presently, there was no conversion on the way out (there is conversion on the way in), so this PR adds conversion when we write data.
The next step will be to change our native structures to be one-based (thanks, Elixir, for not making that configurable) so all we need to deal with in the language server are our data structures.
> Converted range-able response types

- apps/common/lib/lexical/code_unit.ex
- apps/common/lib/lexical/source_file.ex
- apps/common/lib/lexical/source_file/document.ex
- apps/common/test/lexical/code_unit_test.exs
- apps/common/test/lexical/source_file/store_test.exs
- apps/common_protocol/lib/lexical/protocol/conversions.ex
- apps/common_protocol/test/lexical/ranged_test.exs
- apps/protocol/test/lexical/proto_test.exs
- apps/remote_control/lib/lexical/remote_control/completion.ex
- apps/remote_control/test/lexical/remote_control/code_mod/replace_with_underscore_test.exs
- apps/server/lib/lexical/server/code_intelligence/completion/env.ex
- apps/server/lib/lexical/server/project/diagnostics.ex
- apps/server/test/lexical/server/code_intelligence/completion/translations/function_test.exs
- apps/server/test/lexical/server/project/diagnostics/state_test.exs
- apps/server/test/lexical/server/project/diagnostics_test.exs
- apps/server/test/source_file_test.exs
- apps/server/test/support/completion_case.ex
- apps/server/test/support/cursor_support.ex
When I designed lexical, I thought it would be good to have zero-based positions like the LS protocol and elixir's conventions. I thought that getting the compiler to emit zero-based messages would be as simple as adding a compiler setting. However, it's not so easy. In fact, it's impossible at the present moment.
So, we can see the code is starting to get a lot of `line + 1` and `line - 1` kind of code, which stinks.
Combined with the last commit, this changes source files, code units, positions and ranges to be one-based, and we convert from the zero-based language server at the boundaries. Now, the only code that adds or subtracts will be string manipulation code, which we'll likely put behind some kind of interface.
Get ready for a series of off-by-one errors
Fixes #81
> Converted positions to be one-based

- apps/remote_control/lib/lexical/remote_control/build/error.ex
- apps/remote_control/test/lexical/remote_control/build/error_test.exs
Hint is not always available, but when there is a hint, its information is more precise than the context. Currently, when there is a hint, there will be three diagnostics provided. However, I prefer to have only **one diagnostic**.
for example:
```elixir
defmodule ElixirNav do
def foo_middle() do
end
def foo_end() do
def foo() do
end
end
```
The diagnostic of line 10 is enough.
Also, we cannot use the method of adding 1 to highlight the entire line. This can easily cause the range to exceed the total number of lines in the code and highlight the whole file. Instead, we should use:
```
elixir_range =
ExRange.new(
ExPosition.new(line_number, column),
ExPosition.new(min(line_number + 1, file_size), 1)
)
```
This is the preview in VScode.(I verified this in vscode and neovim.)
And this is the …
> Use multiple diagnostics instead of one

- apps/server/lib/lexical/server/project/diagnostics.ex
- apps/server/test/lexical/server/project/diagnostics/state_test.exs
The compilation diagnostics of a test file only come from the compilation of the file. The project compilation (i.e., `MIX_ENV=test mix compile`) will not produce any diagnostics for the test file. Therefore, when you save a problematic test file, it may seem strange that after saving, the error disappears but reappears when you edit it.
This fix ensures that the diagnostics of test files will not be cleared when saved.
> Fix script file diagnostics flushing

- apps/proto/.formatter.exs
- apps/proto/lib/lexical/proto.ex
- apps/proto/lib/lexical/proto/decoders.ex
- apps/proto/lib/lexical/proto/macros/message.ex
- apps/proto/lib/lexical/proto/notification.ex
- apps/proto/lib/lexical/proto/request.ex
- apps/protocol/lib/lexical/protocol/notifications.ex
- apps/protocol/lib/lexical/protocol/requests.ex
- apps/protocol/test/lexical/proto_test.exs
It was unnecessary, since there is only one way to handle requests in lexical.
> Removed Access specifier

- rel/deploy/overlays/start_lexical.sh
The launcher script wasn't starting with the correct environment variables, which caused the default MIX_HOME (~/.mix) to be selected. If this didn't exist, lexical would crash on start with a badmatch error.
Fixes #116
> Fixed: Lecxical won't reliably start under asdf

- .github/workflows/release.yml
Github actions workflow for building and publishing a release of Lexical on every commit.
Publishes the same zip twice with and without the short sha in the file name. The version without the file name is to simplify automation for the likes of vscode auto-install.
Obviously this is a bit hard to test, but I've confirmed it works on my fork.
- Working workflow log: https://github.com/Blond11516/lexical/actions/runs/4775550397/jobs/8489933099
- Corresponding release: https://github.com/Blond11516/lexical/releases/tag/9c0d013
> ci: Add automatic release workflow

- apps/proto/.formatter.exs
- apps/proto/lib/lexical/proto.ex
- apps/proto/lib/lexical/proto/alias.ex
- apps/proto/lib/lexical/proto/macros/meta.ex
- apps/proto/lib/lexical/proto/notification.ex
- apps/proto/lib/lexical/proto/request.ex
- apps/protocol/lib/generated/lexical/protocol/types/cancel/params.ex
- apps/protocol/lib/generated/lexical/protocol/types/definition/params.ex
- apps/protocol/lib/generated/lexical/protocol/types/did_change_configuration/params.ex
- apps/protocol/lib/generated/lexical/protocol/types/did_change_watched_files/params.ex
- apps/protocol/lib/generated/lexical/protocol/types/did_close_text_document/params.ex
- apps/protocol/lib/generated/lexical/protocol/types/did_open_text_document/params.ex
- apps/protocol/lib/generated/lexical/protocol/types/did_save_text_document/params.ex
- apps/protocol/lib/generated/lexical/protocol/types/file_change_type.ex
- apps/protocol/lib/generated/lexical/protocol/types/file_event.ex
- apps/protocol/lib/generated/lexical/protocol/types/log_message/params.ex
- apps/protocol/lib/generated/lexical/protocol/types/show_message/params.ex
- apps/protocol/lib/generated/lexical/protocol/types/text_document/content_change_event.ex
- apps/protocol/lib/lexical/protocol/notifications.ex
- apps/protocol/lib/lexical/protocol/requests.ex
- apps/protocol/mix.exs
- apps/protocol/test/lexical/proto_test.exs
The protocol acutally defines params types for notifications and responses, and we were recapitulating them in their definitions. This PR adds a bunch of the auto-generated types and allows notification/request definitions to reference them. Then the types are consulted to build the request or notification's parameters.
The result is much simpler definitions and less manual work when we need to create new ones.
> Simplified building requests and responses

- .github/workflows/release.yml
As discussed, use timestamps (ISO 8601 without milliseconds, in UTC) as release names instead of commit SHAs to make them more user-friendly.
Example workflow: https://github.com/Blond11516/lexical/actions/runs/4804337258/jobs/8549725577
Example release: https://github.com/Blond11516/lexical/releases/tag/36a6f00
> ci: Use timestamp as release names instead of commit SHAs

- .github/workflows/release.yml
Automatically generate release changelogs to include links to PRs among other things.
Example release with auto-generated changelog: https://github.com/Blond11516/lexical/releases/tag/66ee53c
> ci: Auto-generate release notes

- apps/remote_control/lib/lexical/remote_control/code_mod/format.ex
The function is called with only one argument. Using it like this leads to a crash of the server on save.
> Correct arity of format_string

- .github/workflows/release.yml
Changes the released archives to have the release files at the root rather than under the `_build/dev/rel/lexical` path.
> ci: Remove build directory structure from released archives

- apps/remote_control/lib/lexical/remote_control/code_mod/format.ex
`Code.format_string!/1` returns iodata but
`Lexical.RemoteControl.CodeMod.Diff.diff/2` expected both `unformatted` and `formatted` to be a binary. This changes fix `formatted` to ensure that it's a binary.
> Fix crash due to formatter return iodata not binary

- apps/server/mix.exs
Before lexical stability is achieved, we need to enable `logger_file_backend` in the production environment as well.
Additionally, if the logger_file_backend is not enabled, it will also cause issues with completing `string.|`
> Enable logger_file_backend in prod env

- apps/remote_control/lib/lexical/remote_control/compile_tracer.ex
- apps/remote_control/test/lexical/remote_control/build_test.exs
Modules that aren't auto-loaded would break the compile tracer, as they don't have any functions yet. This change actually loads them from their bytecode, which is given to us and takes about 100us to do. I figure this can go in the compile tracer for now, since this won't happen too often.
Fixes #132
> Fix: Tracing would fail for modules that aren't auto-loaded

- apps/remote_control/lib/lexical/remote_control/build.ex
```elixir
==> remote_control
Compiling 4 files (.ex)
warning: this clause cannot match because a previous clause at line 90 always matches
lib/lexical/remote_control/build.ex:94
Generated remote_control app
==> protocol
Compiling 1 file (.ex)
Generated protocol app
==> server
Compiling 5 files (.ex)
Generated server app
```
> Fix clause mismatching warnning

- apps/remote_control/test/fixtures/project/lib/macros.ex
- apps/server/lib/lexical/server/code_intelligence/completion/translations/callable.ex
- apps/server/lib/lexical/server/code_intelligence/completion/translations/function.ex
- apps/server/lib/lexical/server/code_intelligence/completion/translations/macro.ex
- apps/server/test/lexical/server/code_intelligence/completion/translations/macro_test.exs
We spent a bunch of time working on function completions in a variety of cases, but macro completions still were quite primitive, only completing with the name and arity, which is almost never what you want.
This refactors the logic for building these completions into a `Callable` module so both macros and functions can share their behavior.
Fixes #136
> Refactor: Make callable completions consistent

- apps/server/lib/lexical/server.ex
- apps/server/lib/lexical/server/provider/queue.ex
- apps/server/test/lexical/server/provider/queue_test.exs
I switched to lsp-mode, which sends us cancel _notifications_ which are a thing, and we weren't handling them at all.
Fixes #155
> Handled Cancel Notifications

- apps/common/lib/lexical/document/store.ex
- apps/server/lib/lexical/server.ex
I was getting sporadic deadlocks in the document store since I moved to lsp-mode (it sends a *lot* more didChange updates than eglot), so I'm trying moving writes out of the genserver to see if that helps (it seems to).
I also noticed some troubling messages about not being able to apply didChange events, but that was due to an incorrect log message in the server state, which is also fixed here.
> Addressed deadlocks in Document Store

- apps/common/lib/lexical/document/store.ex
- apps/protocol/lib/lexical/protocol/convertibles/lexical.protocol.types.text_document.content_change_event1.ex
- apps/protocol/test/lexical/protocol/convertibles/lexical.protocol.types.text_document.content_change_event1_test.exs
- apps/server/lib/lexical/server.ex
- apps/server/lib/lexical/server/transport/std_io.ex
- apps/server/test/document_test.exs
After I switched to lsp-mode, my editor was hanging whenever I would update a file using git, and never when I made changes to it in the editor itself. This is because, unlike eglot, when lsp-mode detects a file system change, it sends the entire document over as a replace update, and not an update with many text edits. This would cause the document to go into an infinite loop, and the request would never end, and lexical would become unresponsive.
The reason for this is that the ContentChangeEvent is a type alias with multiple types, one with just a "text" key and one with "text" and a "range" key. The version with a "text" and "range"" key were properly converted to a native Edit by the `Any` convertible implementation, but the version with just the text wasn't properly converted, but …
> Fixed infinite loop in document updates

- apps/common/lib/lexical/completion/environment.ex
- apps/common/lib/lexical/document/lines.ex
- apps/remote_control/lib/lexical/remote_control/completion/result.ex
- apps/server/lib/lexical/server/code_intelligence/completion.ex
- apps/server/lib/lexical/server/code_intelligence/completion/env.ex
- apps/server/lib/lexical/server/code_intelligence/completion/translations/callable.ex
- apps/server/lib/lexical/server/code_intelligence/completion/translations/function.ex
- apps/server/lib/lexical/server/code_intelligence/completion/translations/macro.ex
- apps/server/lib/lexical/server/code_intelligence/completion/translations/module_or_behaviour.ex
- apps/server/lib/lexical/server/code_intelligence/completion/translations/struct.ex
- apps/server/test/document_test.exs
- apps/server/test/lexical/server/code_intelligence/completion/env_test.exs
- apps/server/test/lexical/server/code_intelligence/completion/translations/module_or_behaviour_test.exs
- apps/server/test/lexical/server/code_intelligence/completion_test.exs
This is a two-commit PR. The first does what the title says, and the second fixes a bug in document.
> Alias only returns modules

- apps/common/lib/lexical/document.ex
- apps/server/test/document_test.exs
While talking with Jose Valim about how he could help lexical, we discussed giving a document fragment to a function in Code.Fragment. It seemed to me at the time that one of the functions already there might fit the bill, so I coded up the ability to request a fragment of a document using positions.
Unfortunately, the function in question won't work for us, but I felt that document fragments might be helpful in the future, so here's a PR.
> Added fragment capabilities to document

- apps/remote_control/lib/lexical/remote_control/build/error.ex
- apps/remote_control/test/lexical/remote_control/build/error_test.exs
```elixir
exception #=> %ArgumentError{message: "record :user does not have the key: :email"}
[test/lexical/remote_control/build/error_test.exs:436: Lexical.RemoteControl.Build.ErrorTest."test error_to_
diagnostic/3 handles record missing keys error"/1]
stack #=> [
{Record, :create, 4, [file: 'lib/record.ex', line: 423]},
{Bar, :user, 1, [file: 'expanding macro']},
{Bar, :bar, 0, [file: 'nofile', line: 7]}
]
```
> Fix record missing key's error

- apps/common/lib/lexical/completion/environment.ex
- apps/server/lib/lexical/server/code_intelligence/completion.ex
- apps/server/lib/lexical/server/code_intelligence/completion/env.ex
- apps/server/lib/lexical/server/code_intelligence/completion/translations/module_or_behaviour.ex
- apps/server/lib/lexical/server/code_intelligence/completion/translations/struct.ex
- apps/server/test/lexical/server/code_intelligence/completion/translations/macro_test.exs
- apps/server/test/lexical/server/code_intelligence/completion/translations/module_or_behaviour_test.exs
- apps/server/test/lexical/server/code_intelligence/completion/translations/struct_test.exs
- apps/server/test/lexical/server/code_intelligence/completion_test.exs
- apps/server/test/support/lexical/test/completion_case.ex
I was using naive word-based heuristics to decide several things when completions were requested. This PR removes that approach in favor of a syntax-based approach that should be more robust.
FYI @doughsay
> Removed string-based completion env operations

- .github/workflows/elixir.yml
- apps/remote_control/lib/lexical/remote_control.ex
- apps/remote_control/lib/lexical/remote_control/code_mod/ast.ex
- apps/remote_control/lib/lexical/remote_control/code_mod/replace_with_underscore.ex
- apps/remote_control/mix.exs
- apps/remote_control/test/lexical/remote_control/code_mod/ast_test.exs
- apps/remote_control/test/lexical/remote_control/code_mod/format_test.exs
- apps/remote_control/test/lexical/remote_control/code_mod/replace_with_underscore_test.exs
- apps/remote_control/test/support/lexical/test/code_mod_case.ex
- apps/server/mix.exs
- mix.lock
Code actions were kind of broken, they were unable to process all elements of an elixir document. They would fail if one of the clauses in a case statement had an unused variable, for example. This was due to the old code processing one line at a time.
The new method uses Sourceror Zippers, which can focus on a line of code and process it. Even better, we can use Sourceror patches to generate a list of patches, which can then be turned directly into edits with no string processing at all. This new way of dealing with code is a lot easier than it was previously, and i'm much happier with the API.
> Fixed code actions / improved code mod api

- apps/server/lib/lexical/server/code_intelligence/completion.ex
- apps/server/lib/lexical/server/code_intelligence/completion/env.ex
- apps/server/lib/lexical/server/code_intelligence/completion/translations/module_or_behaviour.ex
- apps/server/lib/lexical/server/code_intelligence/completion/translations/struct.ex
- apps/server/test/lexical/server/code_intelligence/completion/env_test.exs
- apps/server/test/lexical/server/code_intelligence/completion/translations/module_or_behaviour_test.exs
- apps/server/test/lexical/server/code_intelligence/completion/translations/struct_test.exs
- apps/server/test/lexical/server/code_intelligence/completion_test.exs
Struct completion under elixir sense was extremely inconsistent from context to context and even file to file. This was extremely frustrating, as structs might or might not complete depending, seemingly on the time of day.
On the other hand, module completion was pretty consistent, so to fix the issue, prior to sending a document for completion, if we're in a struct reference, we strip it out to get the original module reference back. This means we'll only get module completions from elixir_sense, but we already check for struct references and if we detect that we're in one, turn module completions into struct completions.
I've played around with this and it does seem to fix the problems I was having prior.
> Improved struct completion

- .tool-versions
If a user has set up a `~/.default-mix-commands` file such as mine:
```
local.hex
local.rebar
archive.install hex phx_new
archive.install hex nerves_bootstrap
```
then running `$ asdf install` will fail if the specified erlang version is not installed:
```
Running mix local.hex --force...
No preset version installed for command erl
Please install a version by running one of the following:
asdf install erlang 25.2.1
or add one of the following versions in your config file at /home/juan/code/forks/GitHub/lexical/.tool-versions
erlang 26.0
Running mix local.rebar --force...
No preset version installed for command erl
Please install a version by running one of the following:
asdf install erlang 25.2.1
or add one of the following versions in your config file at …
```
> fix(asdf): change order of installation

- apps/remote_control/lib/lexical/remote_control/completion/result.ex
- apps/remote_control/lib/lexical/remote_control/completion/result/argument_names.ex
- apps/remote_control/test/fixtures/project/lib/default_args.ex
- apps/remote_control/test/lexical/remote_control/completion/result/argument_names_test.exs
- apps/server/lib/lexical/server/code_intelligence/completion/translations/callable.ex
- apps/server/test/lexical/server/code_intelligence/completion/translations/function_test.exs
A couple of updates ago, elixir sense started returning the defaults of arguments along with the names of the arguments. This make our completions much worse, as the arity of the completion didn't match the arity of the function selected *and* the defaults would get pasted into the completion. This meant you had to remove the default from the completion, which was beyond annoying.
These changes strip out defaults and ensure that the arity and arguments match the completion result generated by elixir sense.
> Improve completions with default arguments

- apps/remote_control/lib/lexical/remote_control/completion/result/argument_names.ex
- apps/remote_control/test/fixtures/project/lib/default_args.ex
- apps/remote_control/test/lexical/remote_control/completion/result/argument_names_test.exs
- apps/server/test/lexical/server/code_intelligence/completion/translations/function_test.exs
I was still getting pattern matches when completing arguments (like `%Project{} = project`). This attempts to parse out the argument name, which is assumed to be a variable on either side of the match, and falls back to `arg_#{index}`.
> Pulled out the name of arguments in pattern match args

- .credo.exs
- apps/proto/lib/lexical/proto/macros/struct.ex
- apps/proto/lib/mix/tasks/namespace/abstract.ex
- apps/remote_control/lib/lexical/remote_control/bootstrap.ex
- apps/remote_control/lib/lexical/remote_control/build/error.ex
- apps/remote_control/test/lexical/remote_control/project_node_test.exs
- apps/server/lib/lexical/server/json_rpc_backend.ex
- apps/server/test/document_test.exs
- apps/server/test/lexical/server/project/diagnostics/state_test.exs
- apps/server/test/lexical/server/project/node_test.exs
I often tell people in PRs to "commit to the pipeline", this credo check will do it for me.
Also cleaned up instances where we don't do that in code.
> Added a check for credo pipeline initial argument

- apps/server/lib/lexical/server/code_intelligence/completion/translations/callable.ex
- apps/server/test/lexical/server/code_intelligence/completion/translations/function_test.exs
Lowers the priority of double underscore or default functions when completing functions and captures.
Behavior with this patch: 
Closes #183
> Boost callable completions that are not double underscore/default

- apps/server/lib/lexical/server/code_intelligence/completion/translations/callable.ex
- apps/server/test/lexical/server/code_intelligence/completion/translations/function_test.exs
`behaviour_info/1` is also implemented by default by the compiler, so we should give it a low priority when suggesting completions.
> Reduces behaviour_info/1 priority in completions

- apps/server/lib/lexical/server/code_intelligence/completion/translations/callable.ex
- apps/server/lib/lexical/server/code_intelligence/completion/translations/callback.ex
- apps/server/test/lexical/server/code_intelligence/completion/translations/callback_test.exs
Basic behavior callback completion.  I think this is a good start, but I think there's still more that can be done here, and more thorough tests probably.  Please let me know anything else I should add or cover.
Improvements I'd love to see (but maybe not in this PR) are:
* adding `do/end` to the end of the suggestion snippet for callbacks
* suggest available callbacks at `def|` when inside a module that `use`s a behavior
Thoughts?
> Suggest behavior callbacks

- apps/server/lib/lexical/server/provider/handlers/completion.ex
Completion contexts can be nil, but we assumed they had to be present. This adds a reasonable default.
Co-Authored-By: Steve Cohen <scohen@scohen.org>
> fix: completion context can be null

- apps/common/lib/lexical/completion/builder.ex
- apps/server/lib/lexical/server/code_intelligence/completion/env.ex
- apps/server/lib/lexical/server/code_intelligence/completion/translations/bitstring_option.ex
- apps/server/lib/lexical/server/code_intelligence/completion/translations/callable.ex
- apps/server/lib/lexical/server/code_intelligence/completion/translations/macro.ex
- apps/server/lib/lexical/server/code_intelligence/completion/translations/module_or_behaviour.ex
- apps/server/test/lexical/server/code_intelligence/completion/env_test.exs
- apps/server/test/lexical/server/code_intelligence/completion/translations/function_test.exs
- apps/server/test/lexical/server/code_intelligence/completion/translations/macro_test.exs
- apps/server/test/lexical/server/code_intelligence/completion_test.exs
- apps/server/test/support/lexical/test/completion_case.ex
This pr does two things:
1. Reorders completions so that modules come before functions
2. Refactors boost so that it operates on Completion.Item structs
I think the first thing is a welcome change; it's the default for most LS implementations to sort Modules before functions, and the makes boosting things easier. All items now have a default boost of 0, and items can be boosted with a number from 0-9 to boost items of the same kind, or numbers divisible by 10 to boost across item kinds.
Fixes #202
> Module sorting / Refactor boost

- apps/remote_control/lib/lexical/remote_control/build/state.ex
- apps/remote_control/test/fixtures/project_metadata/config/config.exs
- apps/remote_control/test/lexical/remote_control/build_test.exs
We were not loading project config before compiling, which can cause issues, as seen in #214. The solution is to call loadconfig before compiling
Fixes #214
FYI, @crbelaus
> Load project config before compiling

- apps/remote_control/lib/lexical/remote_control/completion.ex
- apps/remote_control/lib/lexical/remote_control/completion/candidate.ex
- apps/remote_control/lib/lexical/remote_control/completion/candidate/argument_names.ex
- apps/remote_control/test/fixtures/dependency/lib/dependency/structs.ex
- apps/remote_control/test/lexical/remote_control/completion/candidate/argument_names_test.exs
- apps/server/lib/lexical/server/code_intelligence/completion.ex
- apps/server/lib/lexical/server/code_intelligence/completion/translations/bitstring_option.ex
- apps/server/lib/lexical/server/code_intelligence/completion/translations/callable.ex
- apps/server/lib/lexical/server/code_intelligence/completion/translations/callback.ex
- apps/server/lib/lexical/server/code_intelligence/completion/translations/function.ex
- apps/server/lib/lexical/server/code_intelligence/completion/translations/macro.ex
- apps/server/lib/lexical/server/code_intelligence/completion/translations/module_attribute.ex
- apps/server/lib/lexical/server/code_intelligence/completion/translations/module_or_behaviour.ex
- apps/server/lib/lexical/server/code_intelligence/completion/translations/struct.ex
- apps/server/lib/lexical/server/code_intelligence/completion/translations/struct_field.ex
- apps/server/lib/lexical/server/code_intelligence/completion/translations/variable.ex
- apps/server/test/lexical/server/code_intelligence/completion_test.exs
There are a lot of things called `Result` in this codebase. Upon using the completion results, it's pretty clear that they're not really "results", but they're candidates, ready for further refinement by the language server. Hopefully, this nomenclature is more clear.
> Refactor: Completion.Results are now Completion.Candidates

- apps/remote_control/lib/lexical/remote_control/completion/candidate.ex
- apps/server/lib/lexical/server/code_intelligence/completion/translations/map_field.ex
- apps/server/test/lexical/server/code_intelligence/completion/translations/map_field_test.exs
fix this:
```elixir
17:28:51.342 [info] Completion for %Lexical.Document.Position{line: 9, character: 7}
17:28:52.711 [error] ** (ErlangError) Erlang error: {:exception, :function_clause, [{Lexical.RemoteControl.Completion.Candidate, :from_elixir_sense, [%{call?: true, name: "a", origin: nil, subtype: :map_key, type: :field, type_spec: nil}], [file: 'lib/lexical/remote_control/completion/candidate.ex', line: 161]}, {Enum, :"-map/2-lists^map/1-0-", 2, [file: 'lib/enum.ex', line: 1658]}, {Lexical.RemoteControl.Completion, :elixir_sense_expand, 2, []}]}
(kernel 8.5.3) erpc.erl:702: :erpc.call/5
(server 0.1.0) lib/lexical/server/code_intelligence/completion.ex:68: Lexical.Server.CodeIntelligence.Completion.completions/3
(server 0.1.0) lib/lexical/server/code_intelligence/completion.ex:37: …
```
> Support map fields completion

- README.md
- apps/remote_control/lib/lexical/remote_control/plugin/discovery.ex
- mix.exs
- pages/installation.md
Added installation documentation for vscode and emacs
> Docs: Installation

- apps/server/lib/lexical/server/code_intelligence/completion/env.ex
- apps/server/lib/lexical/server/code_intelligence/completion/translations/macro.ex
- apps/server/lib/lexical/server/code_intelligence/completion/translations/struct.ex
- apps/server/test/lexical/server/code_intelligence/completion/env_test.exs
- apps/server/test/lexical/server/code_intelligence/completion/translations/macro_test.exs
- apps/server/test/lexical/server/code_intelligence/completion/translations/struct_test.exs
I believe that only in the context of functions and types will we use the structure of the current module. Therefore, I used these two methods to determine it. In addition, we should keep the completion behavior of structure consistent, so I adopted TextEdit for `%__MODULE__` too.
Fixes #191
> Fix the issue of completing the current module in NeoVim and VScode.

- apps/remote_control/lib/lexical/remote_control/build/state.ex
- apps/remote_control/test/lexical/remote_control/build_test.exs
- projects/lexical_shared/lib/lexical/project.ex
Currently, we only support mix projects. Therefore, `Elixir` and `MixProject` do not provide any additional information. Removing them can make the UI look better and the project name clearer.
> Fix the issue of project name being too long

- apps/plugin_runner/.formatter.exs
- apps/plugin_runner/test/lexical/plugin/runner/coordinator/state_test.exs
- apps/plugin_runner/test/lexical/plugin/runner/coordinator_test.exs
- apps/remote_control/test/lexical/remote_control/build/state_test.exs
The tests here were failing occasionally, and the coordinator test was actually not cleaning up after itself *and* was not testing the right things. This fixes all of those problems.
> Fixing flaky tests

- apps/remote_control/lib/lexical/remote_control/code_mod/ast/aliases.ex
- apps/remote_control/mix.exs
- apps/remote_control/test/lexical/remote_control/build/state_test.exs
- apps/remote_control/test/lexical/remote_control/code_mod/ast/aliases_test.exs
Aliases can fail because Code.Fragment.container_cursor_to_quoted can fail, and I forgot to wrap it with an ok tuple on success.
> Aliases can fail

- .gitignore
- apps/remote_control/lib/lexical/remote_control/bootstrap.ex
- apps/remote_control/test/fixtures/compilation_errors/.gitignore
- apps/remote_control/test/fixtures/compilation_warnings/.gitignore
- apps/remote_control/test/fixtures/project_metadata/.gitignore
- apps/remote_control/test/fixtures/umbrella/.gitignore
- apps/server/.gitignore
- projects/lexical_shared/lib/lexical/project.ex
During the bootstrap process, Lexical creates a `.lexical` directory containing logs and build artifacts. Creating a `.gitignore` in this directory by default means developers don't have to modify their own per-project when using Lexical.
> Generate `.gitignore` for `.lexical` project workspace

- .github/workflows/elixir.yml
This fix will rebuild PLTs on any changes to our deps, or our projects apps' `.ex` files. 
When we merged a PR with changes to the projects directory, it complained about a missing function, but the function was present; this is because changes in the projects directories weren't taken into account when calculating the cache key for the .plt files. This PR adds that calculation.
I still feel like there must be a simpler way to do this, and am welcome to any suggestions.
> Rebuild PLT files on projects dep changes

- projects/lexical_shared/lib/lexical/project.ex
- projects/lexical_shared/test/lexical/project_test.exs
Project names must conform to elixir's rules, and while they're inferred from their paths, they must start with a lowercase character and only contain alphanumeric characters and _. This error is given if you try to start a new project with `mix new`.
This change enforces the same rules.
Fixes #256
> Enforced project name validity

- .github/workflows/release.yml
- Makefile
- README.md
- mix.exs
- pages/installation.md
We noticed that when we'd do a release, we would have to build twice or the server didn't work. This always irked me, as that makes no sense, builds should be deterministic.
What was happening is that the Jason.Encoder protocol was being consolidated, and _this_ breaks the server. Simply removing the consolidation (which is what the double builds did) fixes the problem.
I also reworked the mix.exs file to make it a little easier to understand.
Now we need to research why Jason.Encoder's consolidation breaks things.
> Removed double compilation

- apps/server/test/document_test.exs
- projects/lexical_shared/lib/lexical/document.ex
Document.fragment missed a case when the start line and end line are the same.
> The start line can be the end line

- apps/common/lib/mix/tasks/namespace/beams.ex
Turns out that protocols are consolidated into files named after the protocol, and not the module that's being consolidated. Our old patterns would only apply namespacing to beam files with certain names, which wouldn't catch stuff like `Enumerable`.
A small change to the glob fixes the issue.
Fixes #262
> Fixed protocol consolidation

- apps/remote_control/lib/mix/tasks/module.ex
- apps/remote_control/lib/mix/tasks/namespace.ex
The protocol and proto apps were not being namespaced because I missed appending a trailing '.' to the root module names, this meant both were being excluded.
Circling back, I don't know why I was excluding any of the deps apps from namespacing, as it seems to work fine with it.
It was also possisble to apply namespacing to modules that were already namespaced, so I added a check to ensure that doesn't happen. This was happening for plugins in external projects, as the plugin is a dep, but the code is written to the .lexical directory.
> Namespacing fixes / simplifications

- apps/remote_control/test/fixtures/compilation_errors/mix.exs
- apps/remote_control/test/fixtures/compilation_warnings/mix.exs
- apps/remote_control/test/fixtures/navigations/mix.exs
- apps/remote_control/test/fixtures/parse_errors/mix.exs
- apps/remote_control/test/fixtures/project/mix.exs
- apps/remote_control/test/fixtures/project_metadata/mix.exs
- apps/remote_control/test/fixtures/umbrella/apps/first/mix.exs
- apps/remote_control/test/fixtures/umbrella/apps/second/mix.exs
- apps/remote_control/test/fixtures/umbrella/mix.exs
The noise of 
> warning: redefining module CompilationWarnings.MixProject (current version defined in memory)
/Users/steve/Projects/lexical/apps/remote_control/test/fixtures/compilation_warnings/mix.exs:1
was too much to bear
> Quieted compile warnings in test

- apps/remote_control/lib/lexical/remote_control.ex
- apps/remote_control/lib/lexical/remote_control/project_node.ex
- mix.exs
- rel/deploy/overlays/start_lexical.sh
Prior to this change, running a project in a different version of elixir or erlang than lexical was compiled under would cause an error.
There were two reasons for this:
1. The release is extremely sensitive to the version of elixir / erlang, and would not start if they didn't match. This would happen if include_erts is false.
2. Even if include_erts is true, finding the elixir executable to run would use the inherited environment variables from the server process. ASDF munges the path, and would find the version of elixir that was used to start lexical, not the one the project requests.
The solution is to enable `use_erts` and to undo the path munging that asdf performs. We need to do something similar with rtx.
Fixes #234 
Also fixes #267
> Re-enabled multiple version support

- apps/remote_control/lib/lexical/remote_control/build/state.ex
Some dependencies need to have their configuration set before they're compiled, and we were loading the project's configuration after the compilation step.
All this PR does is change the place loadconfig is called.
Fixes #273
> Loadconfig needs to be called before deps are compiled

- apps/remote_control/lib/lexical/remote_control/completion.ex
- apps/remote_control/lib/lexical/remote_control/completion/candidate.ex
Elixir sense has a seemingly infinite set of maps that it returns from completion, and if we didn't explicitly handle one, the app would crash. This is not acceptable, so I added a default case and a log.
I also had to change the place where candidates were created so nil candidates were omitted.
> Added default candidate case

- apps/server/lib/lexical/server/provider/code_action/replace_with_underscore.ex
Fixed case error where syntactically invalid code is fed to replace underscore.
Fixes 272
> Replace with underscore can fail

- .github/workflows/elixir.yml
- .github/workflows/release.yml
- apps/proto/mix.exs
- apps/protocol/mix.exs
- apps/server/mix.exs
- mix.exs
- pages/installation.md
Updated documentation to be clearer about which versions lexical supports, and ensured all projects would compile under the lowest versions.
> Preparing for 0.2.0 release

- apps/common/lib/future/macro.ex
- apps/common/lib/lexical/ast.ex
- apps/common/test/lexical/ast_test.exs
- apps/remote_control/lib/lexical/remote_control/api.ex
- apps/remote_control/lib/lexical/remote_control/code_intelligence/ast.ex
- apps/remote_control/lib/lexical/remote_control/code_mod/ast/aliases.ex
- apps/remote_control/lib/lexical/remote_control/completion.ex
- apps/remote_control/lib/lexical/remote_control/completion/candidate.ex
- apps/remote_control/test/lexical/remote_control/completion_test.exs
- apps/server/lib/lexical/server/code_intelligence/completion.ex
- apps/server/lib/lexical/server/code_intelligence/completion/env.ex
- apps/server/lib/lexical/server/code_intelligence/completion/translations/bitstring_option.ex
- apps/server/lib/lexical/server/code_intelligence/completion/translations/macro.ex
- apps/server/lib/lexical/server/code_intelligence/completion/translations/struct.ex
- apps/server/lib/lexical/server/code_intelligence/completion/translations/struct_field.ex
- apps/server/test/lexical/server/code_intelligence/completion/env_test.exs
- apps/server/test/lexical/server/code_intelligence/completion/translations/macro_test.exs
- apps/server/test/lexical/server/code_intelligence/completion/translations/struct_field_test.exs
- apps/server/test/lexical/server/code_intelligence/completion/translations/struct_test.exs
There are four commits, Please review them one by one.
With this completion, it means that we no longer need to remember the specific names of fields, and only need to manually trigger the completion.
Fixes #189
> Support Struct fields completion when in struct arguments context

- flake.lock
- flake.nix
- nix/lexical.nix
This adds Nix Flake which (almost) allows usage of the Lexical via `nix run github:lexical-lsp/lexical -- version` (~~the "almost" part is that one need to define `RELEASE_COOKIE=/dev/null` beforehand as `releases/COOKIE` file is removed by Nix for now~~ that is resolved). This allows user of Nix to use Lexical in their environment without writing their own derivation (Nix name for package).
> Add Nix Flake

- apps/remote_control/lib/lexical/remote_control/build/document.ex
- apps/remote_control/lib/lexical/remote_control/build/project.ex
- apps/remote_control/lib/lexical/remote_control/build/state.ex
- apps/remote_control/test/lexical/remote_control/build/error_test.exs
Step 1 of the two step process to make .heex.* and .eex.* files compile.
Pulled out `Build.Project` into its own module, renamed `Build.File` to `Build.Document`
> Refactor: Extracted Build.Project

- apps/common/lib/lexical/code_unit.ex
There was a bit of confusion here about code units / codepoints, which is now fixed. We were always talking about code units, and utf16 either has one 16 bit code unit or two 16 bit code units.
> Fixed code unit / codepoint confusion

- .github/workflows/elixir.yml
- apps/remote_control/lib/lexical/remote_control.ex
- apps/remote_control/lib/lexical/remote_control/project_node.ex
- projects/lexical_shared/lib/lexical/project.ex
As reported in #291, lexical's node names can conflict with other nodes on the same computer.
This PR adds entropy to the project and uses that value to influence the node names of both the manager and the project
Fixes #291 and #91
> Fixed project node naming conflicts

- apps/remote_control/lib/lexical/remote_control/project_node.ex
This was a mistake on our part.
We merged too quickly and didn't have a chance to delete this line.
> Remove logger for debugging port stdin/sdtout

- apps/common/lib/elixir/features.ex
- apps/remote_control/lib/lexical/remote_control/build/document.ex
- apps/remote_control/lib/lexical/remote_control/build/document/compilers/config.ex
- apps/remote_control/test/lexical/remote_control/build/document/compilers/config_test.exs
We were treating configuration files in the project's config directory
like normal elixir source files, but they're slightly different, and
compiling them will cause errors to appear.
This change adds a config compiler that uses Config.Reader to compile
configuration.
Fixes https://github.com/lexical-lsp/lexical/issues/301
> Config compiler

- pages/installation.md
There are many changes in the LSP client between neovim 0.9 and 0.8. Currently, 0.9.1 is the latest stable version.
Fixes #306
> Improve the documentation related to `neovim` installation.

- apps/remote_control/lib/lexical/remote_control.ex
- apps/remote_control/priv/port_wrapper.sh
Hi 👋 
Had an issue locally when both `asdf` and `rtx` were installed, but Elixir/Erlang versions were handled by `rtx`, so that the elixir executable was not found, and looked into it. 
I'm aware it's an unusual case, but feel the changes couldn't hurt. 
My thinking is also that although version managers are installed, they may not be used to handle Elixir/Erlang, in which case the fallback of checking for the executables directly is still handy.
The changes here basically combine the check for a version manager _and_ the executable into one step, also making it possible to use executables installed by different means.
> Handle presense of multiple version managers

- apps/server/lib/lexical/server/code_intelligence/completion/translations/module_or_behaviour.ex
- apps/server/lib/lexical/server/code_intelligence/completion/translations/struct.ex
- apps/server/lib/lexical/server/project/intelligence.ex
- apps/server/test/lexical/server/code_intelligence/completion/translations/module_or_behaviour_test.exs
- apps/server/test/lexical/server/code_intelligence/completion/translations/struct_test.exs
- apps/server/test/lexical/server/project/intelligence_test.exs
- projects/lexical_shared/lib/lexical/formats.ex
- projects/lexical_shared/test/lexical/formats_test.exs
I think this is what we want.
Two things here:
The execution steps of new new algorithm are as follows:
1. If there is only one module within three generations, only that module will be returned, e.g.: `%Lexical.Document.Changes{}`
2. If there are more structs within three generations and the first layer of the struct has ancestor structs, the ancestor structs and more will be mixedly returned, but not the ancestor module.
3. If there are no ancestor structs, only more will be returned.
In addition, we do not return any structs beyond two generations due to `dots_count + 1`.
When our completion is triggered by a dot, ElixirSense still provides us with struct completion, so we need a consistent approach.
Fixes part of #182
> Second attempt to make struct completion more consistent

- apps/plugin_runner/mix.exs
- apps/remote_control/lib/lexical/remote_control/project_node.ex
- config/config.exs
- config/test.exs
- projects/lexical_plugin/config/test.exs
This PR is two commits, the first shuts up logging in test, but I don't understand why it's broken in the first place. More investigation is warranted.
The second cleans up the config files a bit and removes an unhandled message log message.
> Fix extraneous logging in test

- pages/installation.md
Adjusted the paths to `start_lexical.sh`.
The new packaging has moved this shell script into a different location, and that is now reflected in these installation instructions..
> Update paths to start_lexical.sh in installation.md

- apps/common/mix.exs
- apps/common/test/lexical/math_test.exs
- apps/plugin_runner/test/lexical/plugin/runner/coordinator/state_test.exs
- apps/plugin_runner/test/lexical/plugin/runner/coordinator_test.exs
- config/test.exs
- mix.lock
- projects/lexical_shared/mix.exs
This PR fixes a couple of our flaky unit tests. Thank you to whomever put the seed in the output of ExUnit, that was what was needed to reproduce the flakiness.
Fixes #279
> Fix: Flaky tests

- .github/workflows/elixir.yml
- apps/server/test/lexical/server/code_intelligence/completion/translations/struct_field_test.exs
- pages/installation.md
I tried erlang 26.0.2, and lo and behold, it worked with lexical. There were a few unit test failures due to completion results being ordered differently, but otherwise, lexical works great under 26.
Fixes #244
> Support for erlang 26

- pages/installation.md
Fixes Visual Studio Code installation instructions for post lexical packaging rework.
Addition to: https://github.com/lexical-lsp/lexical/pull/318
p.s. Thanks for the amazing work! It's been a joy to use for the past several weeks.
> Fix VSCode installation instructions

- apps/server/lib/mix/tasks/package.ex
I was testing out support for the new packaging structure in vscode and was wondering why nothing was getting extracted from the zip :sweat_smile:
> Fix package task generating empty ZIPs

- apps/common/lib/lexical/vm/versions.ex
- apps/common/test/lexical/vm/versions_test.exs
- apps/remote_control/lib/lexical/remote_control/build/state.ex
- apps/server/lib/lexical/server/application.ex
- apps/server/lib/lexical/server/boot.ex
- apps/server/lib/mix/tasks/package.ex
Lexical now outputs the erlang and elixir versions of the VM that was used to create them. It now checks the build and packaging directories for these versioning files and emits an error message if the vm starts with beam files that won't work.
Fixes #328 and #324
> Added version compatibility check

- README.md
- apps/common/README.md
- apps/common/lib/lexical/vm/versions.ex
- apps/common/mix.exs
- apps/common/test/lexical/vm/versions_test.exs
- apps/proto/README.md
- apps/proto/mix.exs
- apps/protocol/README.md
- apps/protocol/mix.exs
- apps/remote_control/README.md
- apps/remote_control/lib/lexical/remote_control/build/state.ex
- apps/remote_control/mix.exs
- apps/server/README.md
- apps/server/lib/lexical/server/application.ex
- apps/server/lib/lexical/server/boot.ex
- apps/server/lib/mix/tasks/package.ex
- apps/server/mix.exs
- bin/start_lexical.sh
- flake.lock
- mix.exs
- nix/lexical.nix
- projects/lexical_shared/mix.lock
> 0.3.0 Release

- apps/remote_control/lib/lexical/remote_control/api.ex
- apps/remote_control/lib/lexical/remote_control/modules.ex
- apps/remote_control/test/lexical/remote_control/modules_test.exs
- apps/server/lib/lexical/server/code_intelligence/completion.ex
- apps/server/lib/lexical/server/code_intelligence/completion/translations/macro.ex
- apps/server/test/lexical/server/code_intelligence/completion/translations/macro_test.exs
- apps/server/test/lexical/server/code_intelligence/completion/translations/module_or_behaviour_test.exs
- config/test.exs
When using `use`, we would complete any module, even those without `__using__` macros defined.
This PR filters any suggestions inside a `use` directive to ensure that any suggested modules (or a submodule) contain a __using__ macro of arity 1.
One thing that cropped up is that not all modules are loaded when queried, so I had to use `:code.all_available` to generate the module list. This wasn't super duper fast, so I had to put a cache in front of it, which is the large part of this PR.
Another oddity is that I couldn't just send anonymous functions as predicates, so I had to come up with a way to implement filtering logic across distribution, so I did a matchspec-like thingy, which was a bit ugly, so I made some syntax to make it look like function captures.
Fixes #330
> Context-aware "use" completions

- apps/server/lib/lexical/server/code_intelligence/completion/translations/macro.ex
- apps/server/test/lexical/server/code_intelligence/completion/translations/macro_test.exs
- apps/server/test/lexical/server/code_intelligence/completion/translations/struct_test.exs
- apps/server/test/support/lexical/test/completion_case.ex
The defmodule completion snippet now does a best-effort attempt to guess the module name.
The guessing takes into account lib, test and test/support directories, and if it doesn't detect any of them, just uses the file name.
> Suggest a module name for defmodule completion

- .github/workflows/release.yml
Allows the release workflow to update an existing release.
This will let us create releases through Github’s UI without having the workflow fail afterwards.
> Allow release workflow to update existing releases

- apps/remote_control/lib/mix/tasks/namespace/path.ex
- apps/remote_control/lib/mix/tasks/namespace/transform/app_directories.ex
I was using String.replace to apply namespacing to a path. This would cause issues if lexical resided in a directory whose parents had a substring of one of its app names (e.g. language_server).
Instead of using replace, we should only apply namespacing to subdirectories that are exactly equal to one of lexical's apps.
Fixes #341
> Fixed bug in path namespacing

- apps/server/lib/lexical/server/transport/std_io.ex
This (hopefully) fixes #287.
I'm not completely sure why this is occurring, but non-ascii characters were seemingly double-encoded, at least on my system (Ubuntu 22.04 via WSL, VS Code desktop on Windows). I've confirmed with `:io.getopts()` right before `IO.read/2` is called that the encoding is set to `:latin1`, but the result after `JsonRpc.decode/1` was that text would be utf8 double-encoded -- that is, it was what you would expect from:
latin1_data
|> :unicode.characters_to_binary(:latin1, :utf8)
|> :unicode.characters_to_binary(:latin1, :utf8)
This would result in `Document.Line` text containing more bytes than it should, which causes text edits to fail, leading behind random extra bytes.
I don't love this "fix" because it feels very much like a band-aid, not addressing whatever the …
> Convert utf8->latin1 before decoding JSON-RPC payloads

- README.md
The markdown rendering of README is confusing because of the `>` being interpreted as quote start.
**Before this change:**
**After this change:**
> Fix markdown formatting for supported versions

- apps/remote_control/lib/lexical/remote_control/dispatch.ex
- apps/remote_control/lib/lexical/remote_control/dispatch/handler.ex
- apps/remote_control/lib/lexical/remote_control/dispatch/pub_sub.ex
- apps/remote_control/test/lexical/remote_control/dispatch/handler_test.exs
- apps/remote_control/test/lexical/remote_control/dispatch/pub_sub_state_test.exs
- apps/remote_control/test/lexical/remote_control/dispatch_test.exs
As I was integrating indexing into lexical, I kept having to implement genservers that had no other point than to receive messages and take some action when one was received. :gen_event already does this, so I thought it would be nice to have a simple way to implement handler modules in addition to proceses that receive events.
> Moved dispatch to :gen_event

- apps/common/lib/lexical/ast.ex
- apps/remote_control/lib/lexical/remote_control.ex
- apps/remote_control/lib/lexical/remote_control/api/messages.ex
- apps/remote_control/lib/lexical/remote_control/application.ex
- apps/remote_control/lib/lexical/remote_control/build/document/compilers/quoted.ex
- apps/remote_control/lib/lexical/remote_control/dispatch.ex
- apps/remote_control/lib/lexical/remote_control/dispatch/handler.ex
- apps/remote_control/lib/lexical/remote_control/dispatch/handlers/indexing.ex
- apps/remote_control/lib/lexical/remote_control/search/indexer/entry.ex
- apps/remote_control/lib/lexical/remote_control/search/indexer/quoted.ex
- apps/remote_control/lib/lexical/remote_control/search/indexer/source.ex
- apps/remote_control/lib/lexical/remote_control/search/store.ex
- apps/remote_control/test/lexical/remote_control/build/error_test.exs
- apps/remote_control/test/lexical/remote_control/dispatch/handlers/indexer_test.exs
- apps/remote_control/test/lexical/remote_control/dispatch/handlers/indexing_test.exs
- apps/remote_control/test/lexical/remote_control/search/indexer_test.exs
- apps/server/lib/lexical/server.ex
- apps/server/lib/lexical/server/state.ex
- projects/lexical_shared/lib/lexical/document/store.ex
This commit has the following changes:
1. RemoteControl now emits an event when a document has been quoted.
2. Added a handler to listen for the above event, and update the index when a newly quoted document is emitted
3. Wired up workspace file changes so that when a file is created or deleted, it emits an event to RemoteControl
4. When a filesystem create or delete is detcted by the indexing handler, it is either indexed or its information is removed from the index.
I also had to make Document.Store global. This required moving `fetch` back into the GenServer
After the above changes, I can now edit documents and find module definitions and references via the console.
> Integrated indexing into language server

- apps/remote_control/test/lexical/remote_control/search/store_test.exs
Depending on what was run prior, the store test suite might encounter a previously built index, which would make the create index tests fail. The change here deletes the index in a setup_all block, so the test suite starts with an empty index, and keeps the on_exit handler that deletes the index at the end of each test.
> Fixed index store test failure

- apps/server/lib/lexical/server/iex/helpers.ex
I found the `bin/debug_shell.sh` is pretty cool, and I want to debug the current editor's project node. with this function, the debug flow would be:
```elixir
~/Code/lexical add-current-project ❯ _build/dev/package/lexical/bin/debug_shell.sh                  
Erlang/OTP 25 [erts-13.2.2.2] [source] [64-bit] [smp:16:16] [ds:16:16:10] [async-threads:1] [jit:ns]
Interactive Elixir (1.15.4) - press Ctrl+C to exit (type h() ENTER for help)
iex(manager-lexical-37683@127.0.0.1)1> project = current_project()
%LXical.Project{
root_uri: "file:///Users/scottming/Code/lexical",
mix_exs_uri: "file:///Users/scottming/Code/lexical/mix.exs",
mix_project?: true,
mix_env: nil,
mix_target: nil,
env_variables: %{},
project_module: nil,
entropy: "37683"
}
iex(manager-lexical-37683@127.0.0.1)2> …
```
> Add `current_project/1` helper function

- apps/common/lib/lexical/ast/aliases.ex
- apps/common/test/lexical/ast/aliases_test.exs
- apps/remote_control/test/lexical/remote_control/search/indexer/source_test.exs
Aliases would get confused if a module had another block that didn't define another module (like in a DSL). This was because it only popped a single scope at a time, and if several scopes ended on the same line, only the inner scope would be popped. Calling the pop funcion recursively solves the issue.
> Aliases was confused by nested non-module blocks

- pages/installation.md
Adds the helix installation instructions. I am using it myself in Helix and it works like a charm.
Closes #228
> Add Helix installation instructions

- apps/proto/lib/lexical/proto/macros/message.ex
@scohen noticed this while testing #356.
Before:
After:
> Generate correct typespec for LSP messages

- apps/remote_control/lib/lexical/remote_control/search/indexer.ex
- apps/remote_control/lib/lexical/remote_control/search/store.ex
- apps/remote_control/lib/lexical/remote_control/search/store/state.ex
- apps/remote_control/test/lexical/remote_control/dispatch/handlers/indexer_test.exs
- apps/remote_control/test/lexical/remote_control/search/store_test.exs
- apps/server/lib/lexical/server/iex/helpers.ex
Depending on the computer and size of the project being indexed, it was possible for indexing to take longer than the previous 20 second timeout. Additionally, since indexing was blocking the store GenServer, any calls made to the Store during a long indexing would be likely to time out (default GenServer call timeout is 5 seconds).
This PR updates the `Store.State` API to load asynchronously so that the store can continue to respond while indexing occurs in a task, while the indexing itself has had its timeout changed to `:infinity`.
> Async indexing

- .github/workflows/elixir.yml
- apps/common/lib/future/code/typespec.ex
- apps/common/lib/lexical/ast.ex
- apps/common/mix.exs
- apps/common/test/lexical/ast/aliases_test.exs
- apps/common/test/lexical/ast/env_test.exs
- apps/common/test/lexical/ast_test.exs
- apps/remote_control/lib/lexical/remote_control/api.ex
- apps/remote_control/lib/lexical/remote_control/code_intelligence/docs.ex
- apps/remote_control/lib/lexical/remote_control/code_intelligence/docs/entry.ex
- apps/remote_control/lib/lexical/remote_control/code_mod/replace_with_underscore.ex
- apps/remote_control/lib/lexical/remote_control/modules.ex
- apps/remote_control/mix.exs
- apps/remote_control/test/lexical/remote_control/completion_test.exs
- apps/server/lib/lexical/server/code_intelligence/entity.ex
- apps/server/lib/lexical/server/provider/handlers/hover.ex
- apps/server/lib/lexical/server/provider/markdown.ex
- apps/server/mix.exs
- apps/server/test/lexical/server/code_intelligence/completion/builder_test.exs
- apps/server/test/lexical/server/code_intelligence/entity_test.exs
- apps/server/test/lexical/server/provider/handlers/hover_test.exs
- apps/server/test/support/lexical/test/completion_case.ex
- mix.lock
- projects/lexical_test/lib/lexical/test/cursor_support.ex
- projects/lexical_test/lib/lexical/test/range_support.ex
This PR builds on #331, adding hover support for additional entities:
- Structs
- Qualified calls
- Qualified types
Improvements:
- Generally improved formatting for all hover content.
- Respond with range information to support editor highlighting.
- Include callback signatures and docs for modules that are behaviours.
Notes:
- Add vendored `Future.Code.Typespec`, which includes required fixes in `@spec` to make Dialyzer happy.
- Update `:sourceror` dep to the latest commit until a new release is cut. This latest version updates Sourceror's zippers to be a `%Zipper{}` struct and includes fixes/improvements to `Sourceror.get_range/1`.
- `Lexical.Ast` now uses the `unescape: false` option when parsing code. See ba4223df5c4020c3dc6bc104b73c208496837cb7 for more context.
> Improved hover support: Structs, qualified calls and types, more info for modules

- apps/server/lib/lexical/server/configuration.ex
- apps/server/lib/lexical/server/configuration/support.ex
- apps/server/lib/lexical/server/project/progress/state.ex
- apps/server/test/lexical/server/project/progress_test.exs
While walking through how server and client capabilities were managed, I saw some opportunities to refactor the code that manages configuration and client capabilities. The main changes are:
* Rename `Lexical.Server.Configuration.supports?/1` to `client_supports?/1`
* Refactor `client_supports?/1` to not duplicate the set of keys being tracked
* Refactor `Lexical.Server.Configuration.Support` to generate the struct and `new/1` function based on a mapping.
* Change the capability attributes from the format `:thing?` to `:thing`. This is done because the `%Configuration.Support{}` struct is never intended to be accessed directly, but instead through `Configuration.client_supports?/1`, which reads better as `Configuration.client_supports?(:thing)`.
> Refactor client capability tracking

- apps/common/lib/lexical/ast.ex
- apps/common/lib/lexical/ast/aliases.ex
- apps/common/lib/lexical/ast/module.ex
- apps/common/test/lexical/ast/aliases_test.exs
- apps/common/test/lexical/ast_test.exs
- apps/remote_control/lib/lexical/remote_control/search/indexer/extractors/module.ex
- apps/remote_control/test/lexical/remote_control/search/indexer/source_test.exs
The __aliases__ special form defines three types of aliases, and we were not handling one of them properly. This was made apparent to us in issue #378, where the module defined via `defmodule __MODULE__.Child` was not handled properly. This change fixes that issue, and should handle other aliases as well.
Fixes #378
> Made aliases better handle the __aliases__ special form

- apps/remote_control/test/lexical/remote_control/build/document/compilers/eex_test.exs
- apps/remote_control/test/lexical/remote_control/build/document/compilers/heex_test.exs
The previous CI was fine, and I rebased the latest branch, but the merge still fails the test
> Fix the `eex` compiled flaky test

- apps/proto/lib/lexical/proto/field.ex
- apps/protocol/test/lexical/protocol/integration/initialize_test.exs
Zed already supports custom LS for Elixir. I have found an issue with Lexical during startup, and the log displays the following. 
```elixir
10:21:49.299 [info] Application lx_server started at :nonode@nohost
10:21:49.315 [error] Process #PID<0.140.0> terminating
** (UndefinedFunctionError) function nil.parse/1 is undefined
nil.parse(nil)
(lx_proto 0.3.0) lib/lexical/proto/field.ex:23: anonymous fn/4 in LXical.Proto.Field.extract/3
(elixir 1.15.4) lib/enum.ex:4830: Enumerable.List.reduce/3
(elixir 1.15.4) lib/enum.ex:2564: Enum.reduce_while/3
(lx_proto 0.3.0) lib/lexical/proto/field.ex:22: LXical.Proto.Field.extract/3
(lx_protocol 0.3.0) /Users/scottming/Code/lexical/apps/proto/lib/lexical/proto/macros/parse.ex:41: LXical.Protocol.Requests.Initialize.LSP.parse/1
(lx_protocol 0.3.0) …
```
> Fix Field parsing error for zed editor

- apps/remote_control/lib/lexical/remote_control/build/error.ex
- apps/remote_control/test/lexical/remote_control/build/error_test.exs
We haven't handled the `KeyError` case before
```elixir
19:42:14.925 [error] Invalid diagnostic: {:exception, {%FunctionClauseError{module: LXical.RemoteControl.Build.Error, function: :error_to_diagnostic, arity: 4, kind: nil, args: [#LXical.Document<path: "/Users/scottming/Code/lexical/apps/remote_control/test/lexical/remote_control/build/error_test.exs", version: 60, dirty?: true, lines: %Lines<"defmodule Lexical.RemoteControl.Build.ErrorTest do..."(520 lines)>, ...>, %KeyError{key: :c, term: nil, message: "key :c not found"}, [{Foo, :__struct__, 1, [file: ~c"expanding struct
```
> Fix the struct `KeyError` diagnostics

- apps/remote_control/priv/port_wrapper.sh
- bin/start_lexical.sh
`start_lexical.sh` and `port_wrapper.sh` were using different methods to detect the version manager. `start_lexical.sh` was updated more recently, so I standardized on that.
I also refactored the detection function slightly to echo the result instead of setting a global variable, since it was only used in one place and can be easily captured. This should also make it easier to extract this function into a shared utility if we desire.
Finally, `start_lexical.sh` wasn't doing anything to start the program in the background in non-detected version manager case. I don't fully understand why this is necessary in the first place, but I added it for consistency.
> Detect version manager the same way in all scripts

- apps/server/lib/lexical/server/provider/handlers/formatting.ex
Responding with an error can cause clients to display a pop-up or other notification of the failed request. This can be annoying, however, because diagnostics from the failure will already be displayed.
---
This commit was extracted from #375.
> Respond with `nil` instead of an error when formatting fails

- projects/lexical_shared/lib/lexical/project.ex
We were using the project's module to calculate the project's display name. This can be an issue, because this dynamically calculates the configuration, which might change depending on the current directory.
Fixes #412
> Made display name calculation relocatable

- apps/server/lib/lexical/server/code_intelligence/completion.ex
- apps/server/lib/lexical/server/code_intelligence/completion/builder.ex
- apps/server/lib/lexical/server/code_intelligence/completion/translations/bitstring_option.ex
- apps/server/lib/lexical/server/code_intelligence/completion/translations/map_field.ex
- apps/server/lib/lexical/server/code_intelligence/completion/translations/module_attribute.ex
- apps/server/lib/lexical/server/iex/helpers.ex
- apps/server/test/lexical/server/code_intelligence/completion/builder_test.exs
- apps/server/test/lexical/server/code_intelligence/completion/translations/bitstring_option_test.exs
- apps/server/test/lexical/server/code_intelligence/completion/translations/callback_test.exs
- apps/server/test/lexical/server/code_intelligence/completion/translations/function_test.exs
- apps/server/test/lexical/server/code_intelligence/completion/translations/macro_test.exs
- apps/server/test/lexical/server/code_intelligence/completion/translations/map_field_test.exs
- apps/server/test/lexical/server/code_intelligence/completion/translations/module_attribute_test.exs
- apps/server/test/lexical/server/code_intelligence/completion/translations/module_or_behaviour_test.exs
- apps/server/test/lexical/server/code_intelligence/completion/translations/struct_field_test.exs
- apps/server/test/lexical/server/code_intelligence/completion/translations/struct_test.exs
- apps/server/test/lexical/server/code_intelligence/completion/translations/variable_test.exs
After discussing with @scohen yesterday about various issues with completions, we decided that some things would be simplified by always using text edits instead of insertions.
Closes #351.
> Refactor completions to always use text edits

- apps/common/lib/lexical/ast.ex
It doesn't support passing an AST at the moment.
> Fix spec for `Lexical.Ast.cursor_path/2`

- apps/common/lib/lexical/ast.ex
- apps/common/test/lexical/ast_test.exs
The previous implementation required that the innermost node be a leaf, which meant that `path_at` would return `{:error, :not_found}` if the innermost node was indeed a branch, like `|%MyStruct{}`.
This fix means that the path to the `%` node will now be correctly returned in the example above.
> Fix `path_at/2` to allow path to branches if they're innermost

- apps/common/lib/lexical/ast/env.ex
- apps/common/lib/lexical/ast/environment.ex
- apps/common/test/lexical/ast/env_test.exs
- apps/server/lib/lexical/server/code_intelligence/completion.ex
- apps/server/lib/lexical/server/code_intelligence/completion/builder.ex
- apps/server/lib/lexical/server/code_intelligence/completion/translations/macro.ex
- apps/server/lib/lexical/server/code_intelligence/completion/translations/module_attribute.ex
- apps/server/lib/lexical/server/configuration.ex
- apps/server/lib/lexical/server/state.ex
- apps/server/test/lexical/server/code_intelligence/completion/translations/macro_test.exs
- apps/server/test/lexical/server/code_intelligence/completion/translations/module_attribute_test.exs
- apps/server/test/lexical/server/code_intelligence/completion/translations/struct_field_test.exs
- apps/server/test/lexical/server/code_intelligence/completion_test.exs
- apps/server/test/support/lexical/test/completion_case.ex
Depends on #409, which was cherry-picked out of this branch initially to make review easier.
This PR includes a set of fixes and improvements for completions. It's probably best to review commits individually.
Please do pull and build this branch and play with completions locally.
---
Related:
- #400
> Improve completions

- apps/remote_control/lib/lexical/remote_control/code_intelligence/entity.ex
- apps/remote_control/test/lexical/remote_control/code_intelligence/entity_test.exs
Taking `Mix.Task.Compiler.Diagnostic` as an example, the references are inconsistent when the cursor is on `%Mix.Task.|Compiler.Diagnostic{}` compared to when it is on `Mix.Task.|Compiler.Diagnostic`.
I believe that maintaining consistency between them would provide a better user experience and make it easier to extend for future features, such as renaming.
> Make the operational behavior of the ancestors of structures and modules more consistent

- .editorconfig
- .github/workflows/elixir.yml
- apps/remote_control/priv/port_wrapper.sh
- bin/activate_version_manager.sh
- bin/boot.exs
- bin/debug_shell.sh
- bin/start_lexical.sh
- integration/Dockerfile
- integration/README.md
- integration/boot/set_up_asdf.sh
- integration/boot/set_up_lexical.sh
- integration/boot/set_up_rtx.sh
- integration/build.sh
- integration/test.sh
- integration/test_utils.sh
* Add `bin/activate_version_manager.sh`
This script encapsulates detecting, finding, and activating a version manager. Currently asdf and rtx are supported, though more work likely needs to be done to make sure that they can be found/activated in more cases.
* Refactor `bin/start_lexical.sh`
This script now uses `activate_version_manager.sh` to activate the version manager. It additionally ensures that it exits with an error code if any commands run exit non-zero.
* `bin/boot.exs` halts after booting Lexical if `LX_HALT_AFTER_BOOT` is set
* Begin using `shellcheck` and `shfmt` for script linting and formatting
Both of these tools can be installed using asdf/rtx and have editor support through plugins. CI is not currently enforcing that these be used; we can decide on that later.
* Add …
> Refactor shell scripts and add Docker-based integration tests

- apps/remote_control/lib/lexical/remote_control/search/fuzzy/scorer.ex
We were not using the original subject anywhere, and this is available via the key that the scorer entries are held under, so it was duplicate data.
This reduces memory usage of the Search store
> Removed unused data

- apps/remote_control/test/lexical/remote_control/build/document/compilers/eex_test.exs
- apps/remote_control/test/lexical/remote_control/build/document/compilers/heex_test.exs
- apps/remote_control/test/lexical/remote_control/completion_test.exs
- projects/lexical_test/lib/lexical/test/quiet.ex
Quieted most of the noisy tests, though project builds are emitting noise through a mechanism that capture_io can't handle.
Fixes #401
> Quieted noisy tests

- .github/workflows/elixir.yml
- bin/activate_version_manager.sh
- bin/start_lexical.sh
- integration/Dockerfile
- integration/boot/set_up_lexical.sh
- integration/test.sh
- integration/test_utils.sh
Closes #423
Depending on how an editor was started (from command line or other), rtx environment variables could be missing that would cause Lexical to fail to boot. The salient change using both of these commands to activate rtx:
```
eval "$(rtx activate bash)"
eval "$(rtx env)"
```
This ensures that the environment is properly set up, i.e. `$PATH` is as expected.
The additional changes to this commit improve the integration tests and prevents errors from being masked by the system installation.
> Correctly activate rtx during boot

- projects/lexical_shared/lib/lexical/document/path.ex
> Fix specs in `Lexical.Document.Path`

- apps/common/lib/lexical/vm/versions.ex
- apps/server/lib/lexical/server/boot.ex
- apps/server/test/lexical/server/boot_test.exs
This commit makes a few improvements to the errors shown when Lexical boots with incompatible Elixir/Erlang versions:
* Consistent formatting for all errors
* Prevent an exception that would occur if using an incompatible major version (e.g. Elixir 1.12)
* If both Elixir and Erlang are incompatible, show both errors
* Show full range of compatible versions instead of just the range for the current major version
**Example before:**
**Example after:**
> Improve incompatible version errors on boot

- apps/remote_control/lib/lexical/remote_control/search/store/backend.ex
- apps/remote_control/lib/lexical/remote_control/search/store/backends/ets.ex
- apps/remote_control/lib/lexical/remote_control/search/store/backends/ets/state.ex
- apps/remote_control/lib/lexical/remote_control/search/store/state.ex
- apps/remote_control/test/lexical/remote_control/search/store/backends/ets_test.exs
Since we made the store buffer updates, it doesn't make sense to also have the backkends do the same.
> Removed optional synchronization for ETS backend

- apps/server/lib/lexical/server/provider/handlers/hover.ex
- apps/server/test/lexical/server/provider/handlers/hover_test.exs
For especially long module names, the actual function name/signature could be far off to the right. This change puts the module in which the call is defined immediately below the signature, so that the signature itself is always in a consistent location.
> Put module below call signature for hover funs/types

- bin/activate_version_manager.sh
- bin/start_lexical.sh
- integration/Dockerfile
- integration/boot/set_up_asdf.sh
- integration/boot/set_up_rtx.sh
- integration/test.sh
The checks in `activate_version_manager.sh` need explicit `{ }` to prevent `_detect_rtx` from always running. This would cause the script to exit with an error spuriously, which would trigger an error message that was being written to stdio. Because we use stdio as our transport, that would cause the LS client to crash.
This fixes the crash reported in #440. However, it will still run the server using asdf if both asdf and rtx are installed with the correct versions of Elixir.
> Fix crash on boot due to precedence bug and stdio log

- apps/remote_control/lib/lexical/remote_control/bootstrap.ex
- apps/remote_control/lib/lexical/remote_control/project_node.ex
- apps/remote_control/lib/lexical/remote_control/search/store/backends/ets.ex
- apps/remote_control/lib/lexical/remote_control/search/store/state.ex
- projects/lexical_shared/lib/lexical/document/store.ex
Due to all nodes being connected via distribution after the ETS store is enabled, we can no longer register a document store globally with a non-unique name because Document.Store needs to be associated with an editor.
This change creates some entropy when the server starts to make the document store's name unique, and passes that entropy to the project node.
Fixes #425
> Bugfix: Document Store needs to be globally unique

- .github/workflows/elixir.yml
I was running into some [weird compilation issues](https://github.com/lexical-lsp/lexical/actions/runs/6721278415/job/18266663488) that I suspected was due to deps caching. Looking at the CI config, it seemed like the Elixir/OTP versions weren't being used in the cache key, which could cause caches to be shared between runs of different Elixir versions.
It's possible that some of the namespacing stuff we're doing caused the Elixir compiler to not invalidate/re-compile something that needed to be compiled on a different version -- I'm not sure.
Anyways, once I keyed the deps cache off of Elixir/OTP versions, the build started passing.
> Use Elixir and OTP versions in CI cache keys

- apps/remote_control/lib/lexical/remote_control/build/document/compilers/eex.ex
- apps/remote_control/lib/lexical/remote_control/build/document/compilers/heex.ex
- apps/remote_control/lib/lexical/remote_control/build/error.ex
- apps/remote_control/test/lexical/remote_control/build/document/compilers/eex_test.exs
- apps/remote_control/test/lexical/remote_control/build/document/compilers/heex_test.exs
The error comes from EEx's `eval_quoted`. However, the EEx engine cannot directly recognize variables defined with `:let`. This forces me to ignore diagnostics that start with `undefined variable` for both EEx and HEEx files.
Additionally, as I mentioned in the initial PR, HEEx files heavily rely on definitions from other Elixir files. Therefore, when we compile a single file using the HEEx engine, there are bound to be some limitations.
Fixes #460
> Ignore `undefined variables` error for HEEx files

- apps/common/lib/lexical/ast/env.ex
- apps/common/test/lexical/ast/env_test.exs
Erlang remote calls were not being recognized as being in a pipeline context because they're just atoms, and that wasn't included as a valid token inside of pipelines. Thus, `in_context?(x, :pipe)` would return false, and the first arguments to the functions would appear
Fixes #475
> Fix: Erlang function calls in pipes were incorrectly formatted

- apps/remote_control/lib/lexical/remote_control.ex
- apps/server/lib/lexical/server/code_intelligence/completion/builder.ex
- apps/server/test/lexical/server/code_intelligence/completion/translations/interpolation_test.exs
When completing certain things in string interpolations, the prefix can't be processed by the tokenizer, so `token_stream` returns the EOL from the previous line. We used the length of the EOL as the length of the prefix, which was often not enough, so we'd get a stutter when applying the text edit if the prefix was longer than 2 characters.
The fix is to detect the EOL, and in that case, use Code.Fragment to parse the prefix.
Fixes #462
> Fix: Stutter when completing inside string interpolations

- apps/remote_control/lib/lexical/remote_control/build.ex
- apps/remote_control/lib/lexical/remote_control/build/state.ex
- apps/remote_control/lib/lexical/remote_control/mix.ex
- apps/server/lib/lexical/server/project/node.ex
Build directories are now specific to elixir and erlang versions. This allows us to keep artifacts around even if versions change. This helps move us towards not having to do full builds on start.
This PR also deletes builds older than two months that haven't changed to save hard disk space
Fixes #429
> Made build directory specific to elixir and erlang versions

- apps/remote_control/lib/lexical/remote_control/build.ex
- apps/remote_control/lib/lexical/remote_control/build/state.ex
- apps/remote_control/lib/lexical/remote_control/mix.ex
- apps/server/lib/lexical/server/project/node.ex
If the build directory didn't exist (as it didn't in CI), then an exception was raised when we tried to delete it. This would cause remote control to not boot and the whole system would crash around us. 
Simple solution, don't use bang functions.
> Fix: Don't raise an exception if the build directory doesn't exist

- pages/installation.md
It looks like Lexical supports HEEx files and they're included in e.g. Emacs setup instructions, so adding them to
Neovim as well. I can confirm that it works with my installation (macOS, nightly neovim from homebrew).
> Add heex to filetype list for neovim

- apps/common/lib/lexical/ast/env.ex
- apps/common/test/lexical/ast/env_test.exs
- apps/remote_control/lib/lexical/remote_control/completion/candidate.ex
- apps/server/lib/lexical/server/code_intelligence/completion.ex
- apps/server/lib/lexical/server/code_intelligence/completion/translations/callable.ex
- apps/server/lib/lexical/server/code_intelligence/completion/translations/typespec.ex
- apps/server/test/lexical/server/code_intelligence/completion_test.exs
Prior, we were ignoring typespecs as completion candidates because they are only relevant in a couple of places. This adds detection for those places and only emits completion candidates if they're in a type, typep, opaque or spec.
Additionally, while in one of those contexts, it suppresses most other completions, because they are not relevant.
Fixes #473
> Added completions for typespecs

- apps/remote_control/lib/lexical/remote_control/api.ex
- apps/server/lib/lexical/server/provider/handlers/find_references.ex
- apps/server/test/lexical/server/provider/handlers/find_references_test.exs
find-reference is broken on the main branch.
> Fix find-reference

- apps/common/lib/lexical/ast/analysis/analyzer.ex
- apps/server/test/lexical/server/code_intelligence/completion/translations/module_or_behaviour_test.exs
I'm having trouble replicating this in a test, but I was getting an error when I tried completing something like:
```elixir
defmodule Something do
alias Lexical.|
end
```
The error was caused by an exception thrown in analysis due to an incorrect case in its `reify_alias` implementation. The analyzer deals with modules as lists of segments, e.g. `[:Foo, :Bar, :Baz]`, but the macro env requires that they be combined to `Foo.Bar.Baz`.
> Fix module completion error after a dot

- apps/common/lib/elixir/features.ex
- apps/remote_control/lib/lexical/remote_control/build/document.ex
- apps/remote_control/lib/lexical/remote_control/build/isolation.ex
- apps/remote_control/lib/lexical/remote_control/build/project.ex
- apps/remote_control/test/fixtures/compilation_callback_errors/.formatter.exs
- apps/remote_control/test/fixtures/compilation_callback_errors/.gitignore
- apps/remote_control/test/fixtures/compilation_callback_errors/lib/compile_callback_error.ex
- apps/remote_control/test/fixtures/compilation_callback_errors/mix.exs
- apps/remote_control/test/lexical/remote_control/build_test.exs
- apps/remote_control/test/test_helper.exs
- apps/server/lib/lexical/convertibles/lexical.plugin.diagnostic.result.ex
It is possible for compilation to exit, and we were not handling it properly. This was complicated by the fact that builds happen inside a GenServer, so wrapping things in a try/rescue with an exit handler wasn't enough.
Instead, i launched another process that's monitored and awaited by the build genserver. Then any DOWN messages are turned into diagnostics, and reported.
Fixes #504
> Handle compilation exiting

- apps/remote_control/test/test_helper.exs
- apps/server/test/test_helper.exs
- config/test.exs
In `test.exs`, `Logger.configure` is called when the project node starts, which causes log information not to be displayed after Elixir version 1.15. If we only want to ignore excessive logs during test execution, it would be more appropriate to handle this in `test_helpers`.
> Fix the issue of project.log not displaying logs when developing Lexical with version 1.15.

- apps/remote_control/lib/lexical/remote_control/code_intelligence/references.ex
- apps/remote_control/lib/lexical/remote_control/search/indexer/extractors/function_definition.ex
- apps/remote_control/lib/lexical/remote_control/search/indexer/extractors/function_reference.ex
- apps/remote_control/lib/lexical/remote_control/search/indexer/source/reducer.ex
- apps/remote_control/lib/lexical/remote_control/search/store/backends/ets/schemas/v1.ex
- apps/remote_control/test/lexical/remote_control/search/indexer/extractors/function_definition_test.exs
- apps/remote_control/test/lexical/remote_control/search/indexer/extractors/function_reference_test.exs
- apps/server/lib/lexical/server/iex/helpers.ex
- projects/lexical_shared/lib/lexical/formats.ex
- projects/lexical_test/lib/lexical/test/range_support.ex
Find references: Functions
Implemented find references for functions.
Initially, very few references were found, and this was because we
were deduping the index by id. Removing this call allows us to see the
entire project's references, with the notable exception of imported
macros. I believe we'll need to augment the extractor with a
compilation tracer if we wish to see those. The bad news is lexical
takes around 12 seconds to compile, but around 3 seconds to index.
> Find function references

- apps/common/lib/lexical/ast/analysis/import.ex
- apps/remote_control/test/lexical/remote_control/analyzer/imports_test.exs
Fix the problem in `Document.Store` where it terminates due to `import` syntax errors.
```elixir
{LXical.Document.Store, 2} terminating
...
** (EXIT) an exception was raised:
** (Protocol.UndefinedError) protocol Enumerable not implemented for {:o, [_scope_id: #Reference<0.805024100.2513436673.258227>, line: 6, column: 47], nil} of type Tuple
(elixir 1.15.7) lib/enum.ex:1: Enumerable.impl_for!/1
(elixir 1.15.7) lib/enum.ex:166: Enumerable.reduce/3
(elixir 1.15.7) lib/enum.ex:4387: Enum.reduce/3
(lx_common 0.3.0) lib/lexical/ast/analysis/import.ex:22: LXical.Ast.Analysis.Import.expand_selector/1
(lx_common 0.3.0) lib/lexical/ast/analysis/import.ex:17: [LXical.Ast.Analysis.Import.new/3](https://github.com/lexical-lsp/lexical/compare/LXical.Ast.Analysis.Import.new/3)
(lx_common 0.3.0) …
```
> Fix the `expand_selector` in the case of a syntax error.

- apps/proto/.formatter.exs
- apps/proto/lib/lexical/proto.ex
- apps/proto/lib/lexical/proto/request.ex
- apps/proto/lib/lexical/proto/response.ex
- apps/protocol/lib/generated/lexical/protocol/types/lsp_object.ex
- apps/protocol/lib/generated/lexical/protocol/types/message/action_item.ex
- apps/protocol/lib/generated/lexical/protocol/types/show_message_request/params.ex
- apps/protocol/lib/lexical/protocol/json_rpc.ex
- apps/protocol/lib/lexical/protocol/requests.ex
- apps/protocol/lib/lexical/protocol/responses.ex
- apps/server/lib/lexical/server.ex
- apps/server/lib/lexical/server/state.ex
- apps/server/lib/lexical/server/window.ex
We're going to need some sort of confirmation / messaging, so I thought it was the appropriate time to add Window.send_message. This allows us to send a message to the user, and optionally await some kind of response.
To accomplish this, I had to wedge in the notion of a server sent request, which took some doing, as we don't have a mapping from requests to responses (we sort of do now). This required doing some work in the proto layer, as requests didn't have the ability to parse themselves (since they originate from the server).
I tested this in both emacs and vscode, and it seems to work
> Added Window.send_messages

- apps/remote_control/lib/lexical/remote_control/search/store.ex
- apps/remote_control/test/lexical/remote_control/code_intelligence/references_test.exs
- apps/remote_control/test/lexical/remote_control/dispatch/handlers/indexer_test.exs
- apps/remote_control/test/lexical/remote_control/search/store/backends/ets_test.exs
- apps/remote_control/test/lexical/remote_control/search/store_test.exs
Indexing slows down project compilation by 4x, but I've been completely unable to figure out why. This PR works around the issue by waiting for the project to compile before indexing is enabled. I'll explain what I know next.
All I had to go on was the following: The code server had a message queue and the dirty schedulers had elevated levels. The odd thing is that these two things happened _after_ the indexer had completed. Whatever the indexer was doing continued to affect the compiler, even after the indexer was done.
I investigated the following hypothesis
* We were overwhelming the file server with traffic x I disabled any reads and writes, still had the problem
* We were contending on the `:global` locks x I removed the global registrations, the problem persisted
* Indexing was …
> Workaround for indexing performance

- apps/proto/.formatter.exs
- apps/proto/lib/lexical/proto.ex
- apps/proto/lib/lexical/proto/request.ex
- apps/protocol/lib/generated/lexical/protocol/types/code_lens.ex
- apps/protocol/lib/generated/lexical/protocol/types/code_lens/params.ex
- apps/protocol/lib/generated/lexical/protocol/types/execute_command/params.ex
- apps/protocol/lib/generated/lexical/protocol/types/execute_command/registration/options.ex
- apps/protocol/lib/lexical/protocol/requests.ex
- apps/protocol/lib/lexical/protocol/responses.ex
- apps/remote_control/lib/lexical/remote_control/api.ex
- apps/remote_control/lib/lexical/remote_control/api/messages.ex
- apps/remote_control/lib/lexical/remote_control/application.ex
- apps/remote_control/lib/lexical/remote_control/commands/reindex.ex
- apps/remote_control/lib/lexical/remote_control/dispatch/handlers/indexing.ex
- apps/remote_control/lib/lexical/remote_control/search/indexer.ex
- apps/remote_control/test/lexical/remote_control/commands/reindex_test.exs
- apps/remote_control/test/lexical/remote_control/dispatch/handlers/indexer_test.exs
- apps/server/lib/lexical/server/project/search_listener.ex
- apps/server/lib/lexical/server/project/supervisor.ex
- apps/server/lib/lexical/server/provider/handlers.ex
- apps/server/lib/lexical/server/provider/handlers/code_lens.ex
- apps/server/lib/lexical/server/provider/handlers/commands.ex
- apps/server/lib/lexical/server/state.ex
- apps/server/lib/lexical/server/window.ex
- apps/server/test/lexical/server/provider/handlers/code_lens_test.exs
Added a reindex code lens so we can rebuild indexes without resorting to manual operations.
As we build the indexing infrastructure out, we'll likely need to rebuild the index a lot. Presently, this means restarting the server, which can take some time, so I thought i'd add a command to do it instead. I tried using code actions, but this was a bit fraught, so instead, I used a code lens on the project definition in your mix.exs file.
Fixes #517
> Added reindex command

- apps/common/lib/lexical/ast/analysis.ex
- apps/common/test/lexical/ast_test.exs
Today, while writing an alias "as", I unexpectedly discovered that `Document.Store` terminated due to an unmatched error.
```elixir
21:48:27.208 [error] Child :undefined of Supervisor LXical.Server.Provider.Queue.Supervisor terminated
** (exit) exited in: GenServer.call({:via, :global, {LXical.Document.Store, 322}}, {:fetch, "file:///Users/scottming/Code/dummy/lib/dummy.ex", :analysis}, 5000)
** (EXIT) an exception was raised:
** (Protocol.UndefinedError) protocol Enumerable not implemented for {:a, [_scope_id: #Reference<0.3819903562.3914334214.38740>, line: 16, column: 18], nil} of type Tuple
(elixir 1.15.7) lib/enum.ex:1: Enumerable.impl_for!/1
(elixir 1.15.7) lib/enum.ex:166: Enumerable.reduce/3
(elixir 1.15.7) lib/enum.ex:1227: Enum.find_value/3
(lx_common 0.3.0) …
```
> Fix the termination issue of `Document.Store` caused by incomplete syntax errors.

- apps/remote_control/lib/lexical/remote_control/application.ex
- apps/server/test/lexical/server/provider/handlers/code_lens_test.exs
The reindexer was starting up and trying to update a non-existent store, which would crash.
> Only enable the reindexer if indexing is enabled

- apps/common/lib/lexical/ast.ex
- apps/remote_control/lib/lexical/remote_control/analyzer.ex
- apps/remote_control/lib/lexical/remote_control/search/indexer/extractors/function_reference.ex
- apps/remote_control/lib/lexical/remote_control/search/indexer/extractors/module.ex
- apps/remote_control/lib/lexical/remote_control/search/indexer/source/reducer.ex
I initially assumed that the cases where `expand_alias` would fail would be rare, so I did a hard match on `{:ok, alias}`. I was wrong, the cases are much more common, and this is causing irritation for people trying to use indexing. This change logs the cases where expand_alias fails, and skips the entries, which should give better developer experience and should also allow us to see what's causing the failures.
> Properly handle expand_alias failures

- apps/remote_control/lib/lexical/remote_control/commands/reindex.ex
- apps/remote_control/lib/lexical/remote_control/search/indexer.ex
- apps/remote_control/lib/lexical/remote_control/search/indexer/entry.ex
- apps/remote_control/lib/lexical/remote_control/search/indexer/extractors/function_definition.ex
- apps/remote_control/lib/lexical/remote_control/search/indexer/extractors/function_reference.ex
- apps/remote_control/lib/lexical/remote_control/search/indexer/quoted.ex
- apps/remote_control/lib/lexical/remote_control/search/store/backends/ets/schema.ex
- apps/remote_control/lib/lexical/remote_control/search/store/backends/ets/schemas/v1.ex
- apps/remote_control/lib/lexical/remote_control/search/store/backends/ets/state.ex
- apps/remote_control/test/lexical/remote_control/search/store_test.exs
- apps/remote_control/test/support/lexical/test/entry/entry_builder.ex
- projects/lexical_shared/lib/lexical/process_cache.ex
- projects/lexical_shared/test/lexical/process_cache_test.exs
For lexical, the index was using 450MB of disk and consumed about a gig in memory. This commit includes the following changes:
* We stopped duplicating entries in a couple of the records, and now only store them once in the 'by_ref' key. This decreased the index size by 50%, and had no noticable effect on performance.
* Several of the processes had cache entries lying around that caused them to consume quite a bit (hundreds of megs) of memory. I introduced a cache cleaning block and added it to the call sites, and this reduced the memory usage of those processes back to extremely low levels.
* We were storing the erlang and elixir versions on each entry. Now we create separate indexes for each elixir/erlang version pair
In total, lexical was taking around 1gb of memory before these …
> Improved lexical's index efficiency

- apps/remote_control/lib/lexical/remote_control/search/store/backends/ets/schema.ex
- apps/remote_control/lib/lexical/remote_control/search/store/backends/ets/schemas/legacy_v0.ex
- apps/remote_control/lib/lexical/remote_control/search/store/backends/ets/schemas/v1.ex
- apps/remote_control/lib/lexical/remote_control/search/store/backends/ets/state.ex
- apps/remote_control/test/lexical/remote_control/search/store/backends/ets/schema_test.exs
We were reaching into version specific schemas to do certain operations, and it seems like we really want the top-level schema module to do these things instead.
> Made schemas implement a bevaviour

- bin/activate_version_manager.sh
Apparently the author of `rtx` changed its name to `mise` recently (rationale here: https://mise.jdx.dev/rtx.html). When you install `rtx` via `homebrew` and run `brew upgrade`, it automatically changes it to `mise` and with it the `rtx` command is changed to `mise` as well (but everything else works in the same way as `rtx`). This PR supports `mise`.
> Support mise (new name for rtx)

- apps/remote_control/lib/lexical/remote_control/analyzer/aliases.ex
- apps/remote_control/test/lexical/remote_control/analyzer/imports_test.exs
Lots of modules seem to do `unquote(__MODULE__).OtherModule`, and we can support this rather than crash, which is what caused #542
Fixes #542
> Fixed alias crash on unquote

- apps/common/lib/lexical/ast/analysis/import.ex
- apps/common/test/lexical/ast_test.exs
- apps/remote_control/lib/lexical/remote_control/analyzer/imports.ex
- apps/remote_control/test/lexical/remote_control/analyzer/imports_test.exs
If you import `only: :macros`, or `only: :functions`, lexical would crash, because there was no case for `only: :f`. Adding a fallthrough case fixes the issue
> Fixed crash that would happen during imports

- apps/remote_control/lib/lexical/remote_control/code_intelligence/entity.ex
- apps/remote_control/test/lexical/remote_control/code_intelligence/entity_test.exs
Prior, resolve would fail on erlang modules and remote calls because
they're returned as "unquoted atoms".
This commit adds support for completing them.
Fixes https://github.com/lexical-lsp/lexical/issues/533
> Entity resolve erlang modules

- apps/server/lib/lexical/server/state.ex
Prior, it was a boolean, this is incorrect, it needs to be a CodeLens.Options struct.
Fixes #551
> Correctly applied code lens options

- apps/remote_control/lib/lexical/remote_control/bootstrap.ex
- apps/remote_control/lib/lexical/remote_control/project_node.ex
- apps/remote_control/lib/mix/tasks/namespace/transform/configs.ex
- apps/remote_control/mix.exs
- apps/remote_control/test/lexical/remote_control/code_mod/format_test.exs
- apps/server/lib/mix/tasks/package.ex
Had an interesting bug with indexing; The snowflakes generated by remote_control were not compatible with our epoch. This is because we weren't namepsacing the configuration files, and were configuring snowflake rather than lx_snowflake.
This PR adds that namespacing.
> Namespacing: Apply to config scripts 

- apps/remote_control/lib/lexical/remote_control/analyzer.ex
This used to live in Lexical.Ast, but no longer does.
> Correct docs for expand_alias

- apps/remote_control/lib/lexical/remote_control/analyzer.ex
- apps/remote_control/lib/lexical/remote_control/code_intelligence/entity.ex
- apps/remote_control/lib/lexical/remote_control/code_intelligence/references.ex
- apps/remote_control/lib/lexical/remote_control/search/indexer/entry.ex
- apps/remote_control/lib/lexical/remote_control/search/indexer/extractors/function_definition.ex
- apps/remote_control/lib/lexical/remote_control/search/indexer/extractors/function_reference.ex
- apps/remote_control/lib/lexical/remote_control/search/indexer/extractors/module.ex
- apps/remote_control/lib/lexical/remote_control/search/indexer/extractors/module_attribute.ex
- apps/remote_control/lib/lexical/remote_control/search/indexer/source/reducer.ex
- apps/remote_control/lib/lexical/remote_control/search/subject.ex
- apps/remote_control/test/lexical/remote_control/analyzer_test.exs
- apps/remote_control/test/lexical/remote_control/code_intelligence/entity_test.exs
- apps/remote_control/test/lexical/remote_control/code_intelligence/references_test.exs
- apps/remote_control/test/lexical/remote_control/search/indexer/extractors/module_attribute_test.exs
- apps/server/lib/lexical/server/provider/handlers/hover.ex
We now index references and usages of module attributes. Saving the module name with the attribute limits its scope to the contained module, which greatly simplifies indexing and search.
Fixes #472
> Implemented find references for module attributes

- apps/common/lib/lexical/ast/range.ex
- apps/remote_control/lib/lexical/remote_control/code_intelligence/references.ex
- apps/remote_control/lib/lexical/remote_control/search/indexer/extractors/struct_definition.ex
- apps/remote_control/lib/lexical/remote_control/search/indexer/extractors/struct_reference.ex
- apps/remote_control/lib/lexical/remote_control/search/indexer/source/reducer.ex
- apps/remote_control/test/lexical/remote_control/code_intelligence/references_test.exs
- apps/remote_control/test/lexical/remote_control/search/indexer/extractors/struct_definition_test.exs
- apps/remote_control/test/lexical/remote_control/search/indexer/extractors/struct_reference_test.exs
We now index struct definitions and references, including structs created with the various implementations of Kernel.struct
Fixes #560
> Indexing struct definitions and references

- apps/remote_control/lib/lexical/remote_control/search/indexer/extractors/struct_reference.ex
- apps/remote_control/test/lexical/remote_control/search/indexer/extractors/struct_reference_test.exs
Got a report of an indexer crash due to a case clause error in the reducer. It was caused by one of the struct clauses missing an else.
Fixes #573
> Added missing else for with block

- apps/common/lib/lexical/ast/analysis/import.ex
- apps/remote_control/test/lexical/remote_control/analyzer/imports_test.exs
While importing, it was possible to crash lexical analysis by producing invalid import syntax as you were typing. This change improves resilience by handling and ignoring invalid syntax inside the list of imported functions.
Fixes #559
> Improved import resilience

- apps/remote_control/lib/lexical/remote_control/api.ex
- apps/server/lib/lexical/server/provider/handlers/hover.ex
When performing a hover request, we called Entity.resolve, but this is not safe to call from the server project, because the entity cache is not available on the server node, so it will fail (and crash the provider queue). Moveing entity resolution to remote_control fixes the issue
Fixes #572
> Moved entity resolution to remote control

- apps/remote_control/.formatter.exs
- apps/remote_control/lib/lexical/remote_control/application.ex
- apps/remote_control/lib/lexical/remote_control/search/store.ex
- apps/remote_control/lib/lexical/remote_control/search/store/backends/ets.ex
- apps/remote_control/lib/lexical/remote_control/search/store/backends/ets/schema.ex
- apps/remote_control/lib/lexical/remote_control/search/store/backends/ets/state.ex
- apps/remote_control/lib/lexical/remote_control/search/store/backends/ets/wal.ex
- apps/remote_control/test/lexical/remote_control/code_intelligence/references_test.exs
- apps/remote_control/test/lexical/remote_control/dispatch/handlers/indexer_test.exs
- apps/remote_control/test/lexical/remote_control/search/store/backends/ets/schema_test.exs
- apps/remote_control/test/lexical/remote_control/search/store/backends/ets/wal_test.exs
- apps/remote_control/test/lexical/remote_control/search/store/backends/ets_test.exs
- apps/remote_control/test/lexical/remote_control/search/store_test.exs
Our store was using `:ets.tab2file` to write its entries to the filesystem, which would require writing the entire index every time it was called. This is problematic, as updates to the index come in whenever code is added or removed. This would also cause a lot of contention during startup because of the amount of data being read off the filesystem.
This branch introduces a write ahead log, using erlang's built in `disk_logger` module. The idea is that the WAL writes operations to disk before they're applied to ETS, so that when we start up, we first read a checkpoint, then apply the operations one-by-one to get to the prior state.
Note that this approach is in contrast to using Khepri. Khepri is very nice, but it's significantly slower than this approach, and it uses a lot more memory. …
> ETS backend write-ahead log

- apps/remote_control/lib/lexical/remote_control/completion/candidate.ex
When elixir_sense was upgraded, it added an :alias subtype for module completions, which we didn't handle, so all aliases failed to complete.
> Fixed bug due to elixir_sense upgrade

- apps/common/lib/lexical/features.ex
- apps/remote_control/lib/lexical/remote_control/api.ex
- apps/remote_control/lib/lexical/remote_control/api/messages.ex
- apps/remote_control/lib/lexical/remote_control/application.ex
- apps/remote_control/lib/lexical/remote_control/build/project.ex
- apps/remote_control/lib/lexical/remote_control/build/state.ex
- apps/remote_control/lib/lexical/remote_control/code_intelligence/structs.ex
- apps/remote_control/lib/lexical/remote_control/search/store/state.ex
- apps/remote_control/test/lexical/remote_control/build_test.exs
- apps/server/lib/lexical/server/project/intelligence.ex
- apps/server/lib/lexical/server/provider/handlers/code_lens.ex
- apps/server/lib/lexical/server/state.ex
- apps/server/test/lexical/server/provider/handlers/code_lens_test.exs
- apps/server/test/support/lexical/test/completion_case.ex
- pages/installation.md
Thehe last thing that used the forced build was struct discovery. Now that we index struct definitions, we can instead leverage the already built index, and not have to force compile projects when they start.
This has a tremendous impact on startup time. Lexical would take 11 seconds to compile on my system, and now it compiles in 1.9 seconds. The index is ready nearly instantly after that.
This does mean that this is a bit of a rubicon commit, after this, we rely on the index for core functionality, and we can't disable it. As such, I've removed the environment variable, and the feature flag.
> Struct discovery now uses the index

- apps/remote_control/lib/lexical/remote_control/search/store/state.ex
We're not presently using the fuzzy matcher, and it takes up quite a bit of memory in its current incarnation (hundreds of megs).
We'll need it when we do document and workspace symbols, and we'll need to tune it then.
> Disabled fuzzy matcher

- apps/common/lib/lexical/identifier.ex
- apps/remote_control/lib/lexical/remote_control/search/fuzzy.ex
- apps/remote_control/lib/lexical/remote_control/search/indexer.ex
- apps/remote_control/lib/lexical/remote_control/search/store.ex
- apps/remote_control/lib/lexical/remote_control/search/store/backend.ex
- apps/remote_control/lib/lexical/remote_control/search/store/backends/ets.ex
- apps/remote_control/lib/lexical/remote_control/search/store/backends/ets/state.ex
- apps/remote_control/lib/lexical/remote_control/search/store/state.ex
- apps/remote_control/test/lexical/remote_control/search/indexer_test.exs
- apps/remote_control/test/lexical/remote_control/search/store/backends/ets_test.exs
- apps/remote_control/test/lexical/remote_control/search/store_test.exs
There are several places where we're pulling all the entries from the backend, processing them and throwing them out. This creates memory pressure on every process involved in handing the entries.
Instead of that, it makes more sense to expose a reduce function inside the backend that allows you to process the entries however you want, and only the data you care about is pulled through the processes.
This saves around 250mb running the lexical project on my laptop.
> Removed select_all() from backend in favor of a reduce function

- apps/remote_control/lib/lexical/remote_control/search/indexer/entry.ex
- apps/remote_control/test/lexical/remote_control/search/indexer_test.exs
The id on the entry struct can be used to calculate the updated at, since it's a snowflake.
This saves around 10mb on-disk, and around as much in-memory.
> Removed updated_at from the entry struct

- apps/common/lib/lexical/ast.ex
- apps/common/lib/lexical/ast/analysis.ex
- apps/remote_control/lib/lexical/remote_control/analyzer.ex
- apps/remote_control/lib/lexical/remote_control/search/indexer/extractors/module.ex
- apps/remote_control/test/lexical/remote_control/analyzer/aliases_test.exs
- apps/remote_control/test/lexical/remote_control/analyzer_test.exs
- apps/remote_control/test/lexical/remote_control/search/indexer/extractors/module_test.exs
Apparently, defimpls define two module attributes, `@protocol` and `@for`, which we completely missed during analysis.
Fixes #556
> Handled module attributes in defimpl

- apps/remote_control/lib/lexical/remote_control/search/indexer/extractors/module.ex
- apps/remote_control/test/lexical/remote_control/search/indexer/extractors/module_test.exs
We were not detecting a module reference if it used __MODULE__, as in `__MODULE__.Child`. This was due to not recognizing the AST for `__MODULE__` as being a constituent part of a module reference.
Fixes #602
> Detected module references using __MODULE__

- apps/remote_control/lib/lexical/remote_control/commands/reindex.ex
- apps/remote_control/lib/lexical/remote_control/search/store.ex
- apps/remote_control/lib/lexical/remote_control/search/store/backends/ets.ex
These processes weren't getting GC'd very often, because they're not _that_ busy. Tuning the GC interval makes them take up less memory without having to manually trigger GC on a schedule.
Fixes #599
> Bumped garbage collection for some of our more intensive processes

- apps/remote_control/lib/lexical/remote_control/progress.ex
- apps/remote_control/lib/lexical/remote_control/search/indexer.ex
- apps/remote_control/test/lexical/remote_control/search/indexer_test.exs
- apps/server/lib/lexical/server/project/progress/state.ex
The indexer would return a list of entries, and these entries were sent across process boundaries regularly (in the store, and in the reindex action), which would cause their memory usage to swell.
Returning a stream alleviates this pressure, and reduces the memory used by on the lexical project from 425Mb to 290Mb, a fairly significant savings.
Fixes #597
> Made indexer return streams rather than lists

- apps/remote_control/lib/lexical/remote_control/search/indexer.ex
This change ignores root ids when calculating a file's last updated date
> IDs can also be :root

- apps/remote_control/lib/lexical/remote_control/code_intelligence/references.ex
- apps/remote_control/test/lexical/remote_control/code_intelligence/references_test.exs
When you call find references while hovering over `defstruct` calls, it finds references to the struct that the current module defines. Prior, it would result in no results because we don't index defstruct calls.
Fixes #570
> Calling find references on a `defstruct` call finds defined structs

- apps/remote_control/lib/lexical/remote_control/commands/reindex.ex
- apps/remote_control/lib/lexical/remote_control/search/store.ex
- apps/remote_control/lib/lexical/remote_control/search/store/backends/ets.ex
Despite the prior GC tuning, this keeps memory more in check, holding lexical to low-300mb indefinitely.
> GC'd processes every 5 seconds

- apps/remote_control/lib/lexical/remote_control/search/indexer.ex
> Excluded source files in build directory

- bin/start_lexical.sh
The -e option exits immediately on an error, which will cause the command to exit if no version manager is detected. This means we won't try to invoke elixir from the path.
From my limited knowledge of bash, it looks like this command was added in error.
Fixes #615
> Removed -e option

- .github/workflows/nix.yml
- flake.nix
- mix.exs
- nix/hash
This adds `mix nix.hash` command meant to be used by non-Nix users to generate new Nix hash by running build script in Docker. This commands prints out new hash that need to be pasted into `nix/hash` file. It uses Docker and accepts `DOCKER_CMD` environment variable to direct to alternative Docker-compatible executable (like Podman or Nerdctl).
> chore: prepare scripts for updating Nix hash by non-Nix users

- apps/remote_control/lib/lexical/remote_control/build/error.ex
- apps/remote_control/test/lexical/remote_control/build/document/compilers/eex_test.exs
- apps/remote_control/test/lexical/remote_control/build/document/compilers/heex_test.exs
- apps/remote_control/test/lexical/remote_control/build/error_test.exs
- apps/remote_control/test/lexical/remote_control/build_test.exs
The quote character around the variable name was changed, this broke the code action for replace unused variables.
> Fixed unused variable code action

- apps/remote_control/lib/lexical/remote_control/code_intelligence/references.ex
- apps/remote_control/lib/lexical/remote_control/code_intelligence/structs.ex
- apps/remote_control/lib/lexical/remote_control/search/store/state.ex
- apps/remote_control/test/lexical/remote_control/dispatch/handlers/indexer_test.exs
- apps/remote_control/test/lexical/remote_control/search/store_test.exs
Eliminated `{:ok, entries}` tuple wrappers for search outcomes and references, directly returning `entries`
> Refactor search store queries `exact/2` and `fuzzy/2` for simplicity

- README.md
- mix.exs
- pages/architecture.md
- pages/glossary.md
This first commit is basically just an outline for the glossary and an initial set of terms that I thought would be helpful to define.
> Add a glossary

- apps/remote_control/lib/lexical/remote_control/search/store.ex
- apps/remote_control/lib/lexical/remote_control/search/store/backend.ex
- apps/remote_control/lib/lexical/remote_control/search/store/backends/ets.ex
- apps/remote_control/lib/lexical/remote_control/search/store/backends/ets/schemas/v2.ex
- apps/remote_control/lib/lexical/remote_control/search/store/backends/ets/schemas/v3.ex
- apps/remote_control/lib/lexical/remote_control/search/store/backends/ets/state.ex
- apps/remote_control/lib/lexical/remote_control/search/store/state.ex
- apps/remote_control/test/lexical/remote_control/search/store_test.exs
***Description:*** 
This commit adds the `prefix` function to the `Lexical.RemoteControl.Search.Store` module, allowing for searching entries by prefix. It also implements the `find_by_prefix` callback in the `Lexical.RemoteControl.Search.Store.Backends.Ets` module.
***Changes:***
- Added `prefix` function to `Lexical.RemoteControl.Search.Store`
- Implemented `find_by_prefix` callback in `Lexical.RemoteControl.Search.Store.Backends.Ets`
> Add prefix search functionality to the search store

- apps/server/lib/lexical/server/code_intelligence/completion/translations/callback.ex
- apps/server/lib/lexical/server/code_intelligence/completion/translations/macro.ex
- apps/server/test/lexical/server/code_intelligence/completion/translations/callback_test.exs
Callback completions should now expand to their full def-blocks, preceded with an impl tag.
In a module `use`-ing a behaviour, typing `def |` should result in the following completion options:
* `def (define a function)`
* `def callback(args) module_label`
* `(remaining callbacks)`
* Other `def*` macros
> Implement callback completions

- apps/server/lib/lexical/server/code_intelligence/completion.ex
- apps/server/test/lexical/server/code_intelligence/completion_test.exs
Pursuant to: https://discord.com/channels/269508806759809042/918183981344772117/1214563122686206033
> objectuser — Today at 8:20 AM
I'm using Lexical in VSCode. When I'm creating a do block, the first completion is defmodule and there's no completion listed in the pop-up for just do...end. Should I just use user snippets for a do...end block or is there a better way to configure these completions?
(From Elixir Discord)
Fixes include:
* Include partial `d|` in `should_emit_do_end_snippet`
* Add `filter_text: "do"` for more accurate fuzzy matching
This may warrant user-testing across different editors to ensure existing completions remain consistent, as they may convert user-input-over-time to `textDocument/completion` requests differently.
> Fix `do` completing to `defmodule` in VSCode

- apps/remote_control/lib/lexical/remote_control/search/indexer.ex
This significantly speeds up indexing on _very_ large codebases.
Brought down indexing time from ~2 hours to ~2 minutes on the project I tested this on.
> Speed up indexing by not calling `deps_dir` for every file

- apps/remote_control/lib/lexical/remote_control/search/indexer/source/reducer.ex
- apps/remote_control/test/lexical/remote_control/search/indexer/structure_test.exs
While traversing the AST, it's pretty common to not get the position updated consistently. Because of this, it's possible that there might be more than one block that needs to be popped at a time.
We were also not attempting to pop blocks when an expression occurred, which would cause block mismatches in an expression that occurred after a block ended.
> Fixed bug where blocks weren't popped correctly

- projects/lexical_shared/lib/lexical/document/path.ex
- projects/lexical_shared/test/lexical/document/path_test.exs
Pursuant to #641
* match on and handle `untitled:Untitled-N` URIs. Previously they were errantly being treated as file path URIs.
* add `is_binary` guards to `Document.Path` functions. This makes for slightly more explicit errors.
> Fix crashing in unsaved vscode files

- apps/remote_control/lib/lexical/remote_control/code_intelligence/entity.ex
- apps/remote_control/lib/lexical/remote_control/code_intelligence/references.ex
- apps/remote_control/lib/lexical/remote_control/code_intelligence/variable.ex
- apps/remote_control/lib/lexical/remote_control/search/indexer/extractors/variable.ex
- apps/remote_control/lib/lexical/remote_control/search/indexer/source/reducer.ex
- apps/remote_control/test/lexical/remote_control/code_intelligence/references_test.exs
- apps/remote_control/test/lexical/remote_control/code_intelligence/variable_test.exs
- apps/remote_control/test/lexical/remote_control/search/indexer/extractors/variable_test.exs
- apps/remote_control/test/support/lexical/test/extractor_case.ex
- apps/server/lib/lexical/server/provider/handlers/find_references.ex
- apps/server/test/lexical/server/provider/handlers/find_references_test.exs
- projects/lexical_shared/lib/lexical/document/range.ex
This PR implements find references for variables and fixes a couple bugs and missed cases in the variable indexer.
There's a notable edge case present in the implementation. A rebound variable that's assigned to a block will effectively shadow the variable of that name inside the block. I believe this is a limitation of the information we get back from the indexer, so another approach might be necessary in the future if this becomes an issue. An example follows:
```elixir
name = "Stinky"
name = if some_condition() do
"Smelly"
else
name
end
```
Searching for references for the `name` variable on the first line will return no results, but searching for references to the rebind on the second line will return the reference in the `else` clause in the if.
> Find references for variables

- apps/remote_control/lib/lexical/remote_control/completion/candidate.ex
- apps/server/lib/lexical/server/code_intelligence/completion/builder.ex
- apps/server/lib/lexical/server/code_intelligence/completion/translations/callable.ex
* Include `:summary` from elixir_sense callback candidates.
* Append `@spec`'s to them as well.
* Format `:documentation` as markdown in LSP completions.
* Include the type of callable as a completion detail.
> Add summaries to callable completions.

- projects/lexical_shared/lib/lexical/document/position.ex
- projects/lexical_shared/lib/lexical/document/range.ex
We use range and positions a lot, and the default inspect implementations were very wordy. This changes them to:
Range: `LxRange[<<1, 1>>...<<5,1>>]`
Position: `LxPos<<1, 1>>`
> Slimmed down representations of range and position

- apps/remote_control/lib/lexical/remote_control/search/indexer/extractors/function_definition.ex
- apps/remote_control/test/lexical/remote_control/search/indexer/extractors/function_definition_test.exs
There was an issue where function definitions were returning references as well as the definition. This is because the function definition extractor didn't consume the definition AST and passed it to the function reference extractor, which would pick up the references.
> Fixed issue where function definitions were returning references

- apps/server/lib/lexical/server/transport/std_io.ex
- apps/server/test/lexical/server/transport/std_io_test.exs
We would get sporadic failures where the transport would keep reading headers after they were done. This was due to the previous request containing unicode characters at specific locations, which would confuse the transport, since it was reading the body of the request with IO.read, which reads _characters_, but it was passing in the content-length, which is counted in bytes. This would cause us to over-read the body, and consume part of the next body as we were reading the headers, and then the whole thing would fail when we tried to parse the headers.
The change is simple, switch to `binread`, which takes the number of bytes to read.
> FIX: Invalid reads for requests that contain multi-byte characters

- apps/remote_control/lib/lexical/remote_control/build.ex
- apps/remote_control/lib/lexical/remote_control/build/document/compilers/eex.ex
- apps/remote_control/lib/lexical/remote_control/build/document/compilers/elixir.ex
- apps/remote_control/lib/lexical/remote_control/build/document/compilers/heex.ex
- apps/remote_control/lib/lexical/remote_control/code_action/handlers/replace_remote_function.ex
- apps/server/lib/lexical/server/state.ex
- projects/lexical_shared/lib/lexical/document.ex
- projects/lexical_shared/lib/lexical/document/path.ex
- projects/lexical_shared/lib/lexical/document/store.ex
Presently, Lexical reads file extensions to evaluate files as eex, heex, or elixir. This approach doesn't work for documents that haven't been saved to the file system. Consequently unsaved eex and heex files don't receive proper diagnostics.
This commit adds `language_id` to the `Document` struct and sets it when provided by LSP. If not available, the file extension will be used as a fallback.
> Use `languageId` field provided by LSP clients.

- apps/common/lib/lexical/ast/analysis.ex
- apps/remote_control/test/lexical/remote_control/analyzer_test.exs
Our defimpl resolver was not generating the current module name. It was returning the same module as the protocol, which is incorrect
> Fix: Current module not identified in defimpl

- pages/architecture.md
* Use full links to main branch source code rather than hexdocs format.
Resolves #668.
> Fix links on architecture page.

- apps/server/lib/lexical/server/state.ex
* `did_open.text_document` is coming up as nil, but `did_open.lsp.text_document` is present.
> Patch `DidOpen` handler.

- apps/common/lib/lexical/ast/analysis.ex
- apps/remote_control/lib/lexical/remote_control/search/indexer/extractors/module.ex
- apps/remote_control/test/lexical/remote_control/analyzer_test.exs
- apps/remote_control/test/lexical/remote_control/search/indexer/extractors/protocol_test.exs
Added extractors for defimpl and defprotocol blocks. Also added unit tests
Fixes #664
> Added extractors for defimpl and defprotocol

- apps/server/lib/lexical/server/transport/std_io.ex
The change to binread introduced a fairly complicated unicode bug that would cause decoding of messages to partially fail. This was due to the fact that we were previously using read, which would occasionally return unencoded data. We patched this by doing a utf8 -> latin1 conversion, but this would fail once we acutally read the bytes rather than going through elixir's utf8 encoding friendly IO.read functions.
The change here is to get rid of the encoding step, as we're reading the raw bytes as we should.
> Fixing crash when dealing with unicode files

- apps/common/lib/lexical/ast.ex
- apps/common/lib/lexical/ast/analysis.ex
- apps/common/lib/lexical/ast/detection.ex
- apps/common/lib/lexical/ast/detection/alias.ex
- apps/common/lib/lexical/ast/detection/bitstring.ex
- apps/common/lib/lexical/ast/detection/comment.ex
- apps/common/lib/lexical/ast/detection/directive.ex
- apps/common/lib/lexical/ast/detection/function_capture.ex
- apps/common/lib/lexical/ast/detection/import.ex
- apps/common/lib/lexical/ast/detection/pipe.ex
- apps/common/lib/lexical/ast/detection/require.ex
- apps/common/lib/lexical/ast/detection/spec.ex
- apps/common/lib/lexical/ast/detection/struct_field_key.ex
- apps/common/lib/lexical/ast/detection/struct_field_value.ex
- apps/common/lib/lexical/ast/detection/struct_fields.ex
- apps/common/lib/lexical/ast/detection/struct_reference.ex
- apps/common/lib/lexical/ast/detection/type.ex
- apps/common/lib/lexical/ast/detection/use.ex
- apps/common/lib/lexical/ast/env.ex
- apps/common/test/lexical/ast/detection/comment_test.exs
- apps/common/test/lexical/ast_test.exs
- apps/common/test/support/lexical/test/detection_case.ex
- apps/common/test/support/lexical/test/detection_case/suite.ex
- apps/remote_control/lib/lexical/remote_control/code_intelligence/entity.ex
- apps/remote_control/test/lexical/remote_control/code_intelligence/entity_test.exs
- apps/remote_control/test/lexical/remote_control/search/indexer/metadata_test.exs
- apps/remote_control/test/support/lexical/test/code_mod_case.ex
- apps/server/lib/lexical/server/code_intelligence/completion.ex
- apps/server/test/lexical/server/code_intelligence/completion_test.exs
Previously, we would resolve commented out code as if it wasn't commented out, which caused a crash in #638.
Commented out code shouldn't resolve, but finding comments requires calling a different function with a different return shape than `Code.string_to_quoted`. This PR moves to
`Code.string_to_quoted_with_comments` and puts the comment metadata into the analysis struct where it can be queried.
Fixes #638
> Handled comments when resolving locations

- apps/remote_control/lib/lexical/remote_control/search/indexer/extractors/ex_unit.ex
- apps/remote_control/test/lexical/remote_control/search/indexer/extractors/ex_unit_test.exs
We had a test case that was auto-generating tests, and the unquote crashed the exunit indexer because the test name wasn't a literal string.
This change ignores such tests
Fixes #675
> Fix: Non-string test names crash exunit indexer

- .github/workflows/nix.yml
The nix job was failing due to insufficient permissions. This grants write access to the job.
> Granted write permissions

- apps/remote_control/lib/lexical/remote_control/search/indexer/extractors/function_definition.ex
- apps/remote_control/test/lexical/remote_control/code_intelligence/symbols_test.exs
- apps/remote_control/test/lexical/remote_control/search/indexer/extractors/function_definition_test.exs
There's no location information on macro functions, and we needed it for our detail block. This would cause crashes during indexing.
Fixes #680
> Fix: Function definition extractor chokes on macro functions

- .github/workflows/nix.yml
- flake.nix
- nix/hash
The script is expected to fail, so we need to handle that value. This
commit changes Nix script to not fail anymore (it will always succeed)
and it will update `nix/hash` to new value as needed.
Additionally this updates value immediately.
> chore: update Nix workflow to not return error

- apps/common/lib/lexical/ast/detection.ex
- apps/common/lib/lexical/ast/detection/module_attribute.ex
- apps/common/lib/lexical/ast/env.ex
- apps/common/test/lexical/ast/detection/module_attribute_test.exs
- apps/common/test/lexical/ast/detection/pipe_test.exs
- apps/common/test/lexical/ast/env_test.exs
- apps/common/test/support/lexical/test/detection_case/suite.ex
Our environment can now detect when it's in a module attribute context
This will enable us to check for randomly named module attributes and fix some of our longstanding issues.
> Added module attribute detection

- apps/remote_control/test/fixtures/project/lib/behaviours.ex
- apps/server/lib/lexical/server/code_intelligence/completion.ex
- apps/server/test/lexical/server/code_intelligence/completion_test.exs
Only suggest behaviours in `@impl`
Currently, we suggest all modules when in an `@impl` declaration. This
is an opportunity for mistakes. This PR changes the suggestion to
behaviour modules or modules that are ancestors of behaviour modules.
Fixes #437
> Impl suggest behaviours

- apps/server/lib/lexical/server/code_intelligence/completion.ex
- apps/server/test/lexical/server/code_intelligence/completion_test.exs
We received a crash bug that indicated that elixir sense can return nil in the origin of its results (this is why having structs is nice), which wasn't handled by lexical.
The fix is to ensure that origin and full_name are binary. Fixes #686
> Completions: Handled nil origin and full name

- apps/remote_control/lib/lexical/remote_control/search/indexer/extractors/module_attribute.ex
- apps/remote_control/lib/lexical/remote_control/search/subject.ex
- apps/remote_control/test/lexical/remote_control/code_intelligence/symbols_test.exs
- apps/remote_control/test/lexical/remote_control/search/indexer/extractors/module_attribute_test.exs
If you're typing a module attribute before another module attribute, the parser would emit an extra module attribute with the name of `@` in addition to the existing module attribute.
This change ignores module attributes with the name `@`.
Fixes #690
> Fixed crash for in-progress module attributes

- apps/common/lib/lexical/ast/analysis.ex
- apps/common/lib/lexical/ast/analysis/state.ex
- apps/remote_control/lib/lexical/remote_control/analyzer.ex
- apps/remote_control/lib/lexical/remote_control/search/indexer/entry.ex
- apps/remote_control/lib/lexical/remote_control/search/indexer/extractors/module.ex
- apps/remote_control/lib/lexical/remote_control/search/indexer/extractors/module_attribute.ex
- apps/remote_control/lib/lexical/remote_control/search/indexer/extractors/struct_definition.ex
- apps/remote_control/test/lexical/remote_control/analyzer/aliases_test.exs
- apps/remote_control/test/lexical/remote_control/analyzer_test.exs
- apps/remote_control/test/lexical/remote_control/code_intelligence/entity_test.exs
- apps/remote_control/test/lexical/remote_control/code_intelligence/symbols_test.exs
- apps/remote_control/test/lexical/remote_control/search/indexer/extractors/function_definition_test.exs
- apps/remote_control/test/lexical/remote_control/search/indexer/extractors/module_test.exs
- apps/remote_control/test/lexical/remote_control/search/indexer/extractors/protocol_test.exs
- apps/remote_control/test/lexical/remote_control/search/indexer/structure_test.exs
- apps/remote_control/test/support/lexical/test/extractor_case.ex
While trying to enhance the indexing of protocol modules, I found a fairly serious bug with alias / import detection. When we'd encounter a block of code (usually starting with do), we used soureror's detection of start and end. The problem is that it starts that block before the do, so for example, `defmodule MyModule do..` would start at the `defmodule` call.
This meant that the module we were defining starts at the defmodule call, so our current module detection would be off by almost an entire line. This caused errors when builidng module names for protocols and when people would do `defmodule __MODULE__.Child do`.
We were also making nonsensical module names like `Elixir.__MODULE__` when we called `current_module` despite the fact that not all code is inside a module.
Now, module …
> Fixed: Error while calculating block spans

- apps/remote_control/lib/lexical/remote_control/api.ex
- apps/remote_control/lib/lexical/remote_control/code_intelligence/definition.ex
- apps/remote_control/test/fixtures/navigations/lib/my_definition.ex
- apps/remote_control/test/lexical/remote_control/code_intelligence/definition_test.exs
- apps/server/lib/lexical/server/provider/handlers/go_to_definition.ex
- apps/server/test/lexical/server/provider/handlers/go_to_definition_test.exs
> For module definitions, use the `Indexer` version instead of `ElixirSense`

- apps/remote_control/lib/lexical/remote_control/build.ex
Previously we were passing `document.language_id` `HEEX.recognizes?/1`, when it should've been the document struct directly.
> Fix disabling HEEx as-you-type compilation.

- apps/remote_control/lib/lexical/remote_control/code_intelligence/entity.ex
- apps/remote_control/test/lexical/remote_control/code_intelligence/entity_test.exs
In contexts like heex templates, the current module can be nil, but entity didn't account for that, as it was hard matching on {:ok, module}, which caused crashes in things like hover.
Fixes #693
> Current modules can be nil

- apps/protocol/lib/generated/lexical/protocol/types/location/link.ex
- apps/protocol/lib/generated/lexical/protocol/types/workspace/symbol.ex
- apps/protocol/lib/generated/lexical/protocol/types/workspace/symbol/params.ex
- apps/protocol/lib/lexical/protocol/requests.ex
- apps/protocol/lib/lexical/protocol/responses.ex
- apps/remote_control/lib/lexical/remote_control/api.ex
- apps/remote_control/lib/lexical/remote_control/code_intelligence/symbols.ex
- apps/remote_control/lib/lexical/remote_control/code_intelligence/symbols/workspace.ex
- apps/remote_control/lib/lexical/remote_control/search/fuzzy.ex
- apps/remote_control/lib/lexical/remote_control/search/fuzzy/scorer.ex
- apps/remote_control/lib/lexical/remote_control/search/indexer/entry.ex
- apps/remote_control/lib/lexical/remote_control/search/indexer/extractors/module.ex
- apps/remote_control/lib/lexical/remote_control/search/store/state.ex
- apps/remote_control/lib/lexical/remote_control/search/subject.ex
- apps/remote_control/test/lexical/remote_control/code_intelligence/definition_test.exs
- apps/remote_control/test/lexical/remote_control/code_intelligence/symbols_test.exs
- apps/remote_control/test/lexical/remote_control/search/fuzzy/scorer_test.exs
- apps/remote_control/test/lexical/remote_control/search/fuzzy_test.exs
- apps/remote_control/test/lexical/remote_control/search/indexer/extractors/function_definition_test.exs
- apps/remote_control/test/lexical/remote_control/search/indexer/extractors/module_attribute_test.exs
- apps/remote_control/test/lexical/remote_control/search/indexer/extractors/protocol_test.exs
- apps/remote_control/test/lexical/remote_control/search/store_test.exs
- apps/remote_control/test/support/lexical/test/entry/entry_builder.ex
- apps/remote_control/test/test_helper.exs
- apps/server/lib/lexical/server/provider/handlers.ex
- apps/server/lib/lexical/server/provider/handlers/workspace_symbol.ex
- apps/server/lib/lexical/server/provider/queue.ex
- apps/server/lib/lexical/server/state.ex
- projects/lexical_shared/lib/lexical/project.ex
Workspace symbols support. Workspace symbols finds all things that match a query in a project.
> Workspace symbols

- apps/remote_control/lib/lexical/remote_control/code_intelligence/definition.ex
But I don't know how to test this fallback more extensively, because `Patch` also cannot patch a call to a function within a project node, and I also don't want to introduce a dependency on ecto for navigation project.
> Fallback to `ElixirSense` when unable to find any definitions with Indexer

- nix/hash
It seems that there is still issue with autoupdater. It seems that
`main` is completely locked for direct commits, which mean that GitHub
Bot cannot update the hash automatically. I need to review the
possibility to automatically create PR from the GHA to handle that. But
for now we need to update hash manually.
> chore: update FOD hash

- apps/remote_control/lib/lexical/remote_control/search/fuzzy.ex
I noticed that the fuzzy matcher wouldn't match any unit tests. This is because their application is nil, as they're scripts. This change checks for nil applications, and if it finds one, only excludes the mapped entry if the path looks like it comes from a dependencies directory.
Note, the deps directory name is hard coded. I originally queried the project for the deps directory name, but this would include dependencies in the projects directory, which was quite annoying, hence the hard-coding.
> Included non-deps symbols in fuzzy matcher

- apps/remote_control/lib/lexical/remote_control/search/fuzzy/scorer.ex
- apps/remote_control/test/lexical/remote_control/search/fuzzy/scorer_test.exs
- apps/server/lib/lexical/server/provider/handlers/workspace_symbol.ex
If something matches starting after the last period (of a likely module) it is boosted. This makes a match for `MyModule.Structs.User` take precedence over `MyModule.User.Something` while querying for `User`
> Added boost for matches directly following the last period

- apps/common/lib/lexical/code_unit.ex
- apps/common/test/lexical/code_unit_test.exs
- apps/protocol/lib/lexical/protocol/conversions.ex
- apps/protocol/test/lexical/protocol/conversions_test.exs
- apps/server/test/lexical/convertibles/lexical.plugin.diagnostic.result_test.exs
We were previously using `CodeUnit.to_utf16`, which converts a *code unit* in a UTF-8 string to a code unit in the same string encoded as UTF-16, but we were passing in a *character position* which would lead to incorrect conversion of positions if any multi-byte characters were present before the position.
There were two tests of this existing behavior that seem to have been testing the incorrect behavior.
---
I'm marking this PR as draft for now because I'm also going to delete some `CodeUnit` conversion code that we should never be using (like `CodeUnit.to_utf16`) in a separate commit.
> Fix conversion of char positions to UTF-16 code units

- apps/common/lib/lexical/ast/analysis/scope.ex
- apps/remote_control/lib/lexical/remote_control/analyzer.ex
- apps/remote_control/lib/lexical/remote_control/search/indexer/extractors/module.ex
- apps/remote_control/test/lexical/remote_control/search/indexer/extractors/module_test.exs
My prior PR gave aliases ranges, and determined that an alias start at the end of its range. This meant that all the aliases inside a curly-brace defined alias wouldn't be added to the alias mappings until after the closing curly, which meant the aliases indexer wouldn't get the correct module names for them.
The second bug was always there. We look for the first item in the alias segments in the aliases mapping, and return error if it's not there. However, in a multiple alias, you can do alias Foo.{Bar.Baz}. In that instance, Baz, is the last thing in the segment list, and it wouldn't be found.
> Fixed two bugs with alias calculation

- apps/remote_control/lib/lexical/remote_control/api.ex
- apps/remote_control/lib/lexical/remote_control/code_mod/format.ex
- apps/remote_control/lib/lexical/remote_control/commands/reindex.ex
- apps/remote_control/test/lexical/remote_control/code_mod/format_test.exs
RemoteControl has a global project object that's been augmented with extra information, but sometimes we pass server's project over to remote control. The server doesn't have this extra information, and in cases of compilation, it can cause spurious failures, like not being able to find a project's `.formatter.exs`
Fixes #727
> Stopped passing the server project over to remote_control

- apps/common/lib/lexical/ast.ex
- apps/remote_control/lib/lexical/remote_control/code_action.ex
- apps/remote_control/lib/lexical/remote_control/code_action/handlers/organize_aliases.ex
- apps/remote_control/test/lexical/remote_control/code_action/handlers/organize_aliases_test.exs
- apps/server/lib/lexical/server/state.ex
First pass at an opinionated organize aliases code action. All aliases in a given scope are pulled to the top of the scope, or where the first alias occurs and are alphabetized and flattened.
Fixes #94
> Organize aliases

- apps/remote_control/lib/lexical/remote_control/api.ex
- apps/remote_control/lib/lexical/remote_control/completion.ex
- apps/remote_control/test/lexical/remote_control/completion_test.exs
- apps/server/lib/lexical/server/code_intelligence/completion.ex
- apps/server/lib/lexical/server/code_intelligence/completion/builder.ex
- apps/server/test/lexical/server/code_intelligence/completion/builder_test.exs
In preparation for suggesting modules to import, it became apparent we'd need mroe than just the document string going into the completion call. The completion environment seems like a good choice, as it offers the document, analysis, and a host of other features related to figuring out which context you're in.
This also allowed us to push elixir_sense specific logic into the completions module in remote control, further locating it closer to its call site.
> Refactor: Pass env into completion in remote control

- apps/remote_control/lib/lexical/remote_control/code_action/handlers/replace_remote_function.ex
- apps/remote_control/lib/lexical/remote_control/modules.ex
If an erlang module wasn't loaded previously, the code in replace remote function would think it's an elixir module, and then call an invalid function on the module, which would fail with an exception.
> Fix: Edge case for module loading

- apps/remote_control/lib/lexical/remote_control/code_intelligence/definition.ex
- apps/remote_control/lib/lexical/remote_control/code_intelligence/references.ex
- apps/remote_control/lib/lexical/remote_control/code_intelligence/structs.ex
- apps/remote_control/lib/lexical/remote_control/code_intelligence/symbols.ex
- apps/remote_control/lib/lexical/remote_control/search/indexer/entry.ex
- apps/remote_control/lib/lexical/remote_control/search/store.ex
- apps/remote_control/lib/lexical/remote_control/search/store/state.ex
- apps/remote_control/test/lexical/remote_control/code_intelligence/symbols_test.exs
- apps/remote_control/test/lexical/remote_control/dispatch/handlers/indexer_test.exs
- apps/remote_control/test/lexical/remote_control/search/store_test.exs
The store has a variety of states, and can return errors when it is not enabled. In light of this, we should return ok tuples when it is successful to keep the api consistent and make callers aware that they need to handle errors.
In addition, if loading / enabling takes a while, the store can time out when it's being queried, so unless it's enabled, queries will return empty results, and the enabled check uses persistent term.
Fixes #732
> Improved store error handling

- apps/remote_control/lib/lexical/remote_control/code_intelligence/symbols/document.ex
- apps/remote_control/lib/lexical/remote_control/search/indexer/extractors/function_definition.ex
- apps/remote_control/lib/lexical/remote_control/search/indexer/extractors/function_reference.ex
- apps/remote_control/test/lexical/remote_control/code_intelligence/symbols_test.exs
- apps/remote_control/test/lexical/remote_control/search/indexer/extractors/function_definition_test.exs
- apps/remote_control/test/lexical/remote_control/search/indexer/extractors/function_reference_test.exs
Functions created with defdelegate weren't being indexed, so they weren't showing up in find references, document symbols,  or go to definition.
This change emits two entries when it encounters a `defdelegate` call, one for the local function definition in the calling module, and a function reference to the delegated module. One possibly strange thing is that the function that's being created by defdelegate shows up as `def` in document symbols. This is technically correct, you're defining a public function, but it might be confusing in the UI.
Fixes #724
> Indexed delegated functions

- apps/common/lib/lexical/ast/module.ex
- apps/common/test/lexical/ast/module_test.exs
- apps/remote_control/lib/lexical/remote_control/analyzer.ex
- apps/remote_control/lib/lexical/remote_control/build/error.ex
- apps/remote_control/lib/mix/tasks/namespace.ex
When lexical deals with modules, they can either be erlang or elixir modules. However, Module.split will raise an exception when called on an erlang module. We've implemented safe_split in a couple of places, and this centralizes the base logic.
Safe split will return the type of module, and if it's an erlang or elixir module. It also allows the module's components to be either in bianry or atom form.
> Added safe_split to Ast.Module

- apps/server/lib/lexical/server/code_intelligence/completion/builder.ex
- apps/server/test/lexical/server/code_intelligence/completion/builder_test.exs
Sometimes, it is possible for a normal sentence fragment to be valid elixir, as one of our interpid users recently found out, and lexical would crash due to a missing case statement in the completion builder.
Fixes #741
> Fix: Crash when typing english

- apps/remote_control/lib/lexical/remote_control/code_intelligence/definition.ex
- apps/remote_control/lib/lexical/remote_control/search/indexer/entry.ex
- apps/remote_control/lib/lexical/remote_control/search/indexer/extractors/function_definition.ex
- apps/remote_control/lib/lexical/remote_control/search/indexer/extractors/function_reference.ex
- apps/remote_control/test/lexical/remote_control/code_intelligence/definition_test.exs
- apps/remote_control/test/lexical/remote_control/search/indexer/extractors/function_definition_test.exs
And change `go to definition` from elixir-sense to Indexer for functions.
> Returns two definitions for delegate function's definition

- apps/remote_control/lib/lexical/remote_control/code_intelligence/definition.ex
- apps/remote_control/test/lexical/remote_control/code_intelligence/definition_test.exs
After this PR #744 was merged, I spent a whole day using the latest features. In the case of delegates, returning multiple definitions is undoubtedly useful, but in another scenario, such as when there are when clauses, returning multiple definitions is undoubtedly a distraction (in Neovim, I need to press the keys twice more and think about it). Therefore, the solution in this PR is to directly jump to the position of the first function for such cases where there are same-name, same-arity functions in the same file.
> Fix go to definition behavior for same-name, same-arity functions by directing to the first function

- apps/remote_control/lib/lexical/remote_control/code_action.ex
- apps/remote_control/lib/lexical/remote_control/code_action/handlers/remove_unused_alias.ex
- apps/remote_control/test/lexical/remote_control/code_action/handlers/remove_unused_alias_test.exs
This code action removes any unused aliases. It handles both single aliases where it deletes the entire line up to the next line, and multiple aliases, where it deletes the single alias in the list, handling edge cases when it deletes both the last entry in the list, deleting the previous line's comma and when there's only one entry in the list when it deletes the whole alias.
The approach here is much more complicated than I wanted, I described the reasons why it's that way in the module's documentation, hopefully, we can get a fix from sourceror soon and improve this.
> Code Action: Remove unused aliases

- apps/remote_control/lib/lexical/remote_control/completion/candidate.ex
- apps/server/lib/lexical/server/code_intelligence/completion/translations/struct_field.ex
- apps/server/test/lexical/server/code_intelligence/completion/translations/struct_field_test.exs
Fixes #749 
`:type_spec` is already a part of the `elixir_sense_map`, so defining it in `defstruct` is enough.
If the struct doesn't have a type spec, it would show "Field" in my editor probably because that's how it handles `completion.detail == nil`
Let me know if it's more desirable to fall back to some string explicitly, e.g.:
```elixir
builder.plain_text(env, struct_field.name,
detail: struct_field.type_spec || "Field",
label: struct_field.name,
kind: :field
)
```
> Completion: show type spec for struct fields

- apps/common/lib/lexical/ast/analysis.ex
- apps/common/lib/lexical/ast/analysis/scope.ex
- apps/remote_control/lib/lexical/remote_control/code_action.ex
- apps/remote_control/lib/lexical/remote_control/code_action/handlers/add_alias.ex
- apps/remote_control/lib/lexical/remote_control/code_action/handlers/organize_aliases.ex
- apps/remote_control/lib/lexical/remote_control/code_mod/aliases.ex
- apps/remote_control/lib/mix/tasks/namespace/module.ex
- apps/remote_control/test/lexical/remote_control/code_action/handlers/add_alias_test.exs
- apps/remote_control/test/lexical/remote_control/code_mod/aliases_test.exs
- projects/lexical_test/lib/lexical/test/cursor_support.ex
When coding, it is more convenient to type what you mean, and then come back later and clean up things like aliases. This change implements a code action that understands your current editing context and adds aliases as you type. It finds suggestions using our fuzzy matcher (though it has a bit stricter fuzziness), then provides code actions for each suggestion.
It will fix the following alias types:
`Foo.Bar.Baz|` will result in aliases for modules similar to `Baz`
`%Foo.Bar.Baz|{}` will result in aliases similar to `Baz`, but only
those that have structs defined in them
`Foo.Bar.baz.function|` will result in aliases for modules with a
function with a name similar to `function`
This PR also pulled a bunch of common code out of `orgaize_aliases` and moved it to a code mod file, which …
> Code Action: Add alias

- apps/remote_control/lib/lexical/remote_control/code_intelligence/definition.ex
- apps/remote_control/test/fixtures/navigations/lib/macro_struct.ex
- apps/remote_control/test/fixtures/navigations/lib/struct.ex
- apps/remote_control/test/lexical/remote_control/code_intelligence/definition_test.exs
Typedstruct has an alternate syntax for defining a module (whaa?) and we would crash when we didn't recognize this syntax as being related to a module.
Fixes #750
> Fixed: Go to definitions crashes on modules defined via a macro

- apps/remote_control/lib/lexical/remote_control/plugin/runner.ex
Credo seems to have slowed down a bit recently, and it was consistently failing to execute under 2 seconds (but just barely), so I increased timeout to 3 seconds.
> Increased plugin timeouts

- apps/server/lib/lexical/server/code_intelligence/completion/translations/macro.ex
Reordered based on what I believe is most commonly used.
Old order:
test "message"
test "message" do...
test "message", %{} do...
New order:
test "message" do...
test "message", %{} do...
test "message"
> Reorder `test` macro completions

- apps/common/lib/lexical/ast/analysis.ex
- apps/common/lib/lexical/ast/analysis/require.ex
- apps/common/lib/lexical/ast/analysis/scope.ex
- apps/common/lib/lexical/ast/analysis/state.ex
- apps/common/lib/lexical/ast/analysis/use.ex
- apps/remote_control/lib/lexical/remote_control/analyzer.ex
- apps/remote_control/lib/lexical/remote_control/analyzer/requires.ex
- apps/remote_control/lib/lexical/remote_control/analyzer/uses.ex
- apps/remote_control/test/lexical/remote_control/analyzer/requires_test.exs
- apps/remote_control/test/lexical/remote_control/analyzer/uses_test.exs
For the ecto PR, it would be great to only extract schemas if the `Ecto.Schema` module is used, so to help with that, this PR adds uses and requires to the metadata in the analyzer
> Track uses and requires

- apps/common/lib/lexical/ast/analysis.ex
- apps/remote_control/lib/lexical/remote_control/code_intelligence/entity.ex
- apps/remote_control/lib/lexical/remote_control/search/indexer/extractors/ecto_schema.ex
- apps/remote_control/lib/lexical/remote_control/search/indexer/source/reducer.ex
- apps/remote_control/test/lexical/remote_control/code_intelligence/entity_test.exs
- apps/remote_control/test/lexical/remote_control/search/indexer/extractors/ecto_schema_test.exs
We now have an extractor that emits a struct definition where ecto structs are defined.
Fixes #695
> Added struct definition detection for ecto schemas

- apps/server/lib/lexical/server/code_intelligence/completion/translations/callable.ex
- apps/server/test/lexical/server/code_intelligence/completion/translations/function_test.exs
Bang functions were being sorted after non-bang functions because ! is a very low character (the only other printable character smaller is a space). This means that "003_my_function!:002" would be sorted before "003_my_function:002", which isn't really what we want. Changing the separator between the name and arity to space fixes the problem.
> Sorted bang functions after non-bang variants

- apps/common/lib/lexical/ast.ex
- apps/remote_control/lib/lexical/remote_control/code_intelligence/variable.ex
- projects/lexical_shared/lib/lexical/document/position.ex
- projects/lexical_shared/test/lexical/document/position_test.exs
*NB: Re-opening #764 from a branch on this repo instead of from zachallaun/lexical.*
~~This PR currently points to the branch for #768; we need to change that to main after that PR is addressed.~~
> Implement `Position.compare/2`

- projects/lexical_shared/lib/lexical/formats.ex
- projects/lexical_shared/test/lexical/formats_test.exs
I'm working in a project that generates invalid module names, which would crash lexical due to lexical using Module.split, which causes a crash when it gets an invalid module name.
Switched to use `String.split` instead.
> Handled formatting invalid module names

- apps/server/lib/lexical/server.ex
- apps/server/test/lexical/server/task_queue_test.exs
This will fix the issue that appears in lexical.log
```
10:02:38.610 [error] ** (FunctionClauseError) no function clause matching in LXical.Server.Provider.Handlers.DocumentSymbols.handle/2 
(lx_server 0.5.0) lib/lexical/server/provider/handlers/document_symbols.ex:13: LXical.Server.Provider.Handlers.DocumentSymbols.handle...
(lx_server 0.5.0) lib/lexical/server/task_queue.ex:77: anonymous fn/4 in LXical.Server.TaskQueue.State.as_task/2
(elixir 1.17.1) lib/task/supervised.ex:101: Task.Supervised.invoke_mfa/2
(elixir 1.17.1) lib/task/supervised.ex:36: Task.Supervised.reply/4
```
> Fix: give proper argument to `TaskQueue.add/2` in Server.handle_message

- apps/remote_control/lib/lexical/remote_control/project_node.ex
Doesn't fix #788, but should at least have it restart properly.
To fix the root cause, the project itself needs to be diagnosed.
> handle other cases where project node goes down

- apps/common/lib/elixir/features.ex
- apps/remote_control/lib/lexical/remote_control/search/store/backends/ets/schemas/v3.ex
Fixes #788.
We've had mysterious OTP 27 crashes for quite some time now, but I was finally able to track it down to what I believe is a bug in `:ets`. When the `:compressed` table option is used, the system either segfaults or crashes with a memory-related error on any call that traverses the entire table. In our case, it was a call to `:ets.foldl/3`, but other full traversals like `:ets.tab2list/1` or `:ets.tab2file/2` also crash.
The temporary fix to get things working is to just not use `:compressed` on OTP 27. Unfortunately, this has a *very* sizeable impact on memory:
```elixir
[
total: 200081864,
processes: 97217168,
processes_used: 97187736,
system: 102864696,
atom: 1466705,
atom_used: 1452046,
binary: 2958496,
code: 35956838,
ets: 14065992 # 14MB
]
[
total: 481878632,
processes: …
```
> Fix crashes on OTP 27 by disabling ETS table compression

- apps/common/lib/lexical/ast.ex
- apps/remote_control/lib/lexical/remote_control/build/document/compilers/elixir.ex
- apps/remote_control/lib/lexical/remote_control/build/document/compilers/quoted.ex
- apps/remote_control/test/lexical/remote_control/build/document/compilers/quoted_test.exs
- apps/remote_control/test/lexical/remote_control/build_test.exs
- projects/lexical_shared/lib/lexical/document.ex
Lexical's as-you-type compilation and error reporting works by parsing the AST after a small period of quiescence and then compiling it with `Code.compile_quoted/2`. This runs top-level forms, however, so a `.exs` script that performs side-effects when run, e.g. creating or deleting a file, would have them run repeatedly unless you wrap them in a `def` inside a module.
The goal, then, becomes reporting on as many errors/warnings as possible without running top-level forms.
The current approach here is to chunk all top-level forms into "safe" and "unsafe", where safe forms are only `defmodule/use/import/require/alias`. Safe forms stay at the top level, while unsafe forms are wrapped to prevent their execution. Concretely, this script:
```elixir
import Foo
call_1()
defmodule Bar do
...
end …
```
> Don't run top-level code in `.exs` files

- apps/remote_control/lib/lexical/remote_control.ex
- apps/remote_control/test/test_helper.exs
`:net_kernel.start/1` [is deprecated](https://www.erlang.org/doc/apps/kernel/net_kernel.html#start/1) in favor of `:net_kernel.start/2`, which was introduced in OTP 24.3. As that's the oldest version of OTP we support, we can use the new version.
The defaults with the new 2-arity version are the same, so nothing really changes here.
> Use non-deprecated `:net_kernel.start/2`

- .iex.namespaced.exs
This makes it just a little bit easier to run code in IEx when connected to a running project.
> Alias `LXical` as `Lexical` in IEx

- apps/remote_control/mix.exs
- mix.lock
Elixir sense was doing a compile-time check for a certain feature, and since Lexical is built on an older version of elixir than it often runs on, the check ended up being wrong. We submitted a PR to elixir_sense and now can fix the bug.
> Upgrade elixir_sense

- .github/workflows/nix.yml
Fixes #816. 
Also, `nix build` is run on the last step, to ensure the Nix package can be built successfully.
> Update the Nix hash on PR, not on the main branch

- apps/remote_control/lib/lexical/remote_control/build/document/compilers/config.ex
- apps/remote_control/lib/lexical/remote_control/build/error.ex
- apps/remote_control/lib/lexical/remote_control/build/error/location.ex
- apps/remote_control/test/lexical/remote_control/build/document/compilers/config_test.exs
- integration/boot/set_up_mise.sh
Only some exceptions raised when evaluating a config file using `Config.Reader.eval!/3` were being converted into diagnostics -- any others would result in a function clause error in the config compiler's private `to_result/2`. This function clause error would then be caught and result in another function clause error down the line, the eventual result of which was that diagnostics for config files would be incorrect.
> Convert all exceptions in config files into diagnostics

- apps/remote_control/lib/lexical/remote_control/mix.ex
- apps/server/lib/lexical/server/task_queue.ex
Fixed two bottlenecks in the server. 
1. The mix lock was using a much more contentious build lock rather than its own lock.
2. Using `Task.Supervisor.terminate_child` was causing timeouts when bulk operations happen.
> Server bottlenecks

- apps/remote_control/lib/lexical/remote_control/build.ex
- apps/remote_control/lib/lexical/remote_control/build/state.ex
- apps/remote_control/test/lexical/remote_control/build/state_test.exs
- apps/server/lib/lexical/convertibles/lexical.plugin.diagnostic.result.ex
- projects/lexical_shared/lib/lexical/document/store.ex
This commit seeks to improve the performance under batch operations by holding off compilations until after a period of quiescence. Prior, we were building every 100 or so milliseconds, but this would cause builds to happen during batch operations.
Instead, this PR dramatically simplifies the build process to utilize timeouts to detect a quiet period after which builds can commence.
I also found a missed case while transforming diagnostics into elixir that caused crashes that took down the project node. I was unaware that the uri of a diagnostic can be nil (how?!?).
Prior to this PR, mass renames would never finish in emacs, and now they can.
> Improve performance under batch operations

- pages/installation.md
related to: https://github.com/lexical-lsp/lexical/issues/803
i was looking around for an optimal pattern (for example [here](https://github.com/neovim/nvim-lspconfig/blob/ff97d376b1d22b2eaf9274605531babf0cd0cf21/doc/lspconfig.txt#L355) and [here](https://github.com/neovim/nvim-lspconfig/blob/ff97d376b1d22b2eaf9274605531babf0cd0cf21/doc/server_configurations.md)) any my conclusion as of now is:
- it's quite hard to avoid opinionated example.
- for what it's worth, majority of example configs are rather simple.
- good example configuration probably should target first-time user (more experienced user will likely have their own patterns to follow and experience to implement those).
i did some basic testing with `v0.7.0` compiled against `Elixir 1.17.0 (compiled with Erlang/OTP 27)`.
> simplify default config

- .iex.exs
Ensures that `:observer` can be started from iex. Wrapped in try rescue in case the erlang install being used doesn't have wx/observer.
> add Mix.ensure_application!(:observer) to .iex.exs

- apps/common/lib/elixir/features.ex
Re enables compression for erlang 27.1, as the bug with ets compression was fixed.
> [chore] Allow compression for erlang >= 27.1

- apps/remote_control/lib/lexical/remote_control/code_intelligence/references.ex
- apps/remote_control/test/lexical/remote_control/code_intelligence/references_test.exs
Prior, find references would take the arity into account. This was because in elixir, a function is defined by its name and its arity. However in practice, you more than not want to see a all the calls of a function with a given name rather than a specific head. This is especially true for functions with default arguments.
As a result, this change looks for functions with a given name and any arity.
> [feat] Loosen find_references

- apps/remote_control/lib/lexical/remote_control/code_intelligence/symbols.ex
- apps/remote_control/lib/lexical/remote_control/code_intelligence/symbols/document.ex
- apps/remote_control/test/lexical/remote_control/code_intelligence/symbols_test.exs
If a module had multiple heads for a function that only differed in parameter pattern matches, document symbols was very cluttered. This change groups functions in a module by their name and arity, with each implementation nested in that grouping. This allows editors to collapse function groups to save space.
This change also removes any whitespace or linebreaks from function names.
> [feat] Group functions by name + type + arity in document symbols

- apps/server/lib/lexical/server/code_intelligence/completion/translations/callable.ex
- apps/server/test/lexical/server/code_intelligence/completion/translations/macro_test.exs
Closes #832.
This solution is imperfect because it requires the prefix to end exactly with `Kernel.`
However it works in most cases because:
* Completions are usually requested at the point of `Kernel.|`
* Completions are cached by clients for the next few characters.
In the exceptional rare case where a user copy/pastes something like `Kernel.=|` and requests a completion, these won't show. Not a perfectly correct solution, but our handling of syntax macros is already a matter of taste, so ¯\\\_(ツ)\_/¯
> Show syntax macro completions when `Kernel.` is prefixed to the cursor.

- apps/common/lib/future/mix/tasks/format.ex
- apps/common/lib/lexical/ast/env.ex
- apps/remote_control/lib/lexical/remote_control.ex
- apps/remote_control/lib/lexical/remote_control/build/project.ex
- apps/remote_control/lib/lexical/remote_control/code_mod/format.ex
- apps/remote_control/lib/lexical/remote_control/completion.ex
- apps/server/lib/lexical/server/code_intelligence/completion.ex
- apps/server/lib/lexical/server/task_queue.ex
- mix.lock
- nix/hash
- projects/lexical_shared/lib/lexical/debug.ex
This commit fixes a number of performance related issues, and reworks formatting so it's lock-free and able to be used with format-on-save in any editor. The fixes are:
* We only call deps.compile if the vm changes directories during compilation. This dramatically speeds up compiling erlang deps.
* Adds a timing helper to time blocks of code
* Precalculates contexts around the cursor. Fetching the current context was called once for every completion item. This meant that for large modules, like Enum, hundreds of context calculations were happening.
* Reworked formatting: Jose added a couple of options to Mix.Tasks.Format.formatter_for_file that allow us to not need to be in the project context in order for formatting to work. This enables lock-free formatting which makes the amount of …
> Performance oriented fixes.
